include ./chess_define.makefile
.PHONY:all

all:${CHESS_PROTOCGEN_FILE}

${PROTOCOL_CS_EXTEND_CHESS_3001_H} ${PROTOCOL_CS_EXTEND_CHESS_3001_CPP} : ${PROTOCOL_CS_EXTEND_CHESS_3001_PROTO}
	mkdir -p ${PROTOCGEN_FILE_PATH}/chess_3001
	${PROTOC} $^ -I${THIRD_PARTY_INC_PATH} -I${PROTOCOL_CS_EXTEND_CHESS_3001_PATH} -I${PROTOCOL_COMM_PATH}   -I${PROTOCOL_KERNEL_PATH}\
			--cpp_out=${PROTOCGEN_FILE_PATH}/chess_3001
	cp ${PROTOCOL_CS_EXTEND_CHESS_3001_H} ${PROTOCOL_CS_EXTEND_CHESS_3001_CPP} ${GAME_SRC_PATH}/src/NFGameLogic/NFGameQZNNPlugin_3001 -rf
	
${PROTOCOL_CS_EXTEND_CHESS_3002_H} ${PROTOCOL_CS_EXTEND_CHESS_3002_CPP} : ${PROTOCOL_CS_EXTEND_CHESS_3002_PROTO}
	mkdir -p ${PROTOCGEN_FILE_PATH}/chess_3002
	${PROTOC} $^ -I${THIRD_PARTY_INC_PATH} -I${PROTOCOL_CS_EXTEND_CHESS_3002_PATH} -I${PROTOCOL_COMM_PATH}   -I${PROTOCOL_KERNEL_PATH}\
			--cpp_out=${PROTOCGEN_FILE_PATH}/chess_3002
	cp ${PROTOCOL_CS_EXTEND_CHESS_3002_H} ${PROTOCOL_CS_EXTEND_CHESS_3002_CPP} ${GAME_SRC_PATH}/src/NFGameLogic/NFGameTBNNPlugin_3002 -rf	

${PROTOCOL_CS_EXTEND_LHD_4001_H} ${PROTOCOL_CS_EXTEND_LHD_4001_CPP} : ${PROTOCOL_CS_EXTEND_LHD_4001_PROTO}
	mkdir -p ${PROTOCGEN_FILE_PATH}/lhd_4001
	${PROTOC} $^ -I${THIRD_PARTY_INC_PATH} -I${PROTOCOL_CS_EXTEND_LHD_4001_PATH} -I${PROTOCOL_COMM_PATH}   -I${PROTOCOL_KERNEL_PATH}\
			--cpp_out=${PROTOCGEN_FILE_PATH}/lhd_4001
	cp ${PROTOCOL_CS_EXTEND_LHD_4001_H} ${PROTOCOL_CS_EXTEND_LHD_4001_CPP} ${GAME_SRC_PATH}/src/NFGameLogic/NFGameLongHuPlugin_4001 -rf


	
	
	