// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_svr_email.proto

#ifndef PROTOBUF_proto_5fsvr_5femail_2eproto__INCLUDED
#define PROTOBUF_proto_5fsvr_5femail_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "yd_fieldoptions.pb.h"
#include "proto_common.pb.h"
#include "proto_cs_email.pb.h"
// @@protoc_insertion_point(includes)

namespace proto_ff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

class Proto_GSMailCreateReq;
class Proto_SGMailCreateRsp;
class Proto_LTSMailListReq;
class Proto_STLMailListRsp;
class Proto_LTSMailReadReq;
class Proto_STLMailReadRsp;
class Proto_STLMailAutoPushRsp;
class Proto_LTSMailDelReq;
class Proto_STLMailDelRsp;
class Proto_OtherTSMailCreateReq;
class Proto_STOtherMailCreateRsp;
class Proto_LTSMailGetItemReq;
class Proto_STLMailGetItemRsp;
class Proto_STLMailReadItemReq;
class Proto_LTSMailReadItemRsp;

enum Proto_EmailSvrMsgID {
  NF_LTS_MAIL_LIST_REQ = 235,
  NF_STL_MAIL_LIST_RSP = 236,
  NF_LTS_MAIL_READ_REQ = 237,
  NF_STL_MAIL_READ_RSP = 238,
  NF_LTS_MAIL_DEL_REQ = 239,
  NF_STL_MAIL_DEL_RSP = 240,
  NF_OtherTS_MAIL_CREATE_REQ = 241,
  NF_STOther_MAIL_CREATE_RSP = 242,
  NF_STL_MAIL_MAIL_AUTO_PUSH_RSP = 243,
  NF_LTS_MAIL_GET_ITEM_REQ = 244,
  NF_STL_MAIL_GET_ITEM_RSP = 245,
  NF_STL_MAIL_READ_ITEM_REQ = 246,
  NF_LTS_MAIL_READ_ITEM_RSP = 247
};
bool Proto_EmailSvrMsgID_IsValid(int value);
const Proto_EmailSvrMsgID Proto_EmailSvrMsgID_MIN = NF_LTS_MAIL_LIST_REQ;
const Proto_EmailSvrMsgID Proto_EmailSvrMsgID_MAX = NF_LTS_MAIL_READ_ITEM_RSP;
const int Proto_EmailSvrMsgID_ARRAYSIZE = Proto_EmailSvrMsgID_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto_EmailSvrMsgID_descriptor();
inline const ::std::string& Proto_EmailSvrMsgID_Name(Proto_EmailSvrMsgID value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto_EmailSvrMsgID_descriptor(), value);
}
inline bool Proto_EmailSvrMsgID_Parse(
    const ::std::string& name, Proto_EmailSvrMsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto_EmailSvrMsgID>(
    Proto_EmailSvrMsgID_descriptor(), name, value);
}
// ===================================================================

class Proto_GSMailCreateReq : public ::google::protobuf::Message {
 public:
  Proto_GSMailCreateReq();
  virtual ~Proto_GSMailCreateReq();

  Proto_GSMailCreateReq(const Proto_GSMailCreateReq& from);

  inline Proto_GSMailCreateReq& operator=(const Proto_GSMailCreateReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_GSMailCreateReq& default_instance();

  void Swap(Proto_GSMailCreateReq* other);

  // implements Message ----------------------------------------------

  Proto_GSMailCreateReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_GSMailCreateReq& from);
  void MergeFrom(const Proto_GSMailCreateReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint64 role_id() const;
  inline void set_role_id(::google::protobuf::uint64 value);

  // optional .proto_ff.tbUserMailDetail role_mail = 2;
  inline bool has_role_mail() const;
  inline void clear_role_mail();
  static const int kRoleMailFieldNumber = 2;
  inline const ::proto_ff::tbUserMailDetail& role_mail() const;
  inline ::proto_ff::tbUserMailDetail* mutable_role_mail();
  inline ::proto_ff::tbUserMailDetail* release_role_mail();
  inline void set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_GSMailCreateReq)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_role_mail();
  inline void clear_has_role_mail();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 role_id_;
  ::proto_ff::tbUserMailDetail* role_mail_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_GSMailCreateReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_SGMailCreateRsp : public ::google::protobuf::Message {
 public:
  Proto_SGMailCreateRsp();
  virtual ~Proto_SGMailCreateRsp();

  Proto_SGMailCreateRsp(const Proto_SGMailCreateRsp& from);

  inline Proto_SGMailCreateRsp& operator=(const Proto_SGMailCreateRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_SGMailCreateRsp& default_instance();

  void Swap(Proto_SGMailCreateRsp* other);

  // implements Message ----------------------------------------------

  Proto_SGMailCreateRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_SGMailCreateRsp& from);
  void MergeFrom(const Proto_SGMailCreateRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint64 role_id() const;
  inline void set_role_id(::google::protobuf::uint64 value);

  // optional .proto_ff.tbUserMailDetail role_mail = 2;
  inline bool has_role_mail() const;
  inline void clear_role_mail();
  static const int kRoleMailFieldNumber = 2;
  inline const ::proto_ff::tbUserMailDetail& role_mail() const;
  inline ::proto_ff::tbUserMailDetail* mutable_role_mail();
  inline ::proto_ff::tbUserMailDetail* release_role_mail();
  inline void set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail);

  // optional int32 result = 3;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 3;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_SGMailCreateRsp)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_role_mail();
  inline void clear_has_role_mail();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 role_id_;
  ::proto_ff::tbUserMailDetail* role_mail_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_SGMailCreateRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_LTSMailListReq : public ::google::protobuf::Message {
 public:
  Proto_LTSMailListReq();
  virtual ~Proto_LTSMailListReq();

  Proto_LTSMailListReq(const Proto_LTSMailListReq& from);

  inline Proto_LTSMailListReq& operator=(const Proto_LTSMailListReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_LTSMailListReq& default_instance();

  void Swap(Proto_LTSMailListReq* other);

  // implements Message ----------------------------------------------

  Proto_LTSMailListReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_LTSMailListReq& from);
  void MergeFrom(const Proto_LTSMailListReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_email.Proto_CSMailListReq cs_req = 2;
  inline bool has_cs_req() const;
  inline void clear_cs_req();
  static const int kCsReqFieldNumber = 2;
  inline const ::proto_email::Proto_CSMailListReq& cs_req() const;
  inline ::proto_email::Proto_CSMailListReq* mutable_cs_req();
  inline ::proto_email::Proto_CSMailListReq* release_cs_req();
  inline void set_allocated_cs_req(::proto_email::Proto_CSMailListReq* cs_req);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_LTSMailListReq)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_cs_req();
  inline void clear_has_cs_req();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_email::Proto_CSMailListReq* cs_req_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_LTSMailListReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STLMailListRsp : public ::google::protobuf::Message {
 public:
  Proto_STLMailListRsp();
  virtual ~Proto_STLMailListRsp();

  Proto_STLMailListRsp(const Proto_STLMailListRsp& from);

  inline Proto_STLMailListRsp& operator=(const Proto_STLMailListRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STLMailListRsp& default_instance();

  void Swap(Proto_STLMailListRsp* other);

  // implements Message ----------------------------------------------

  Proto_STLMailListRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STLMailListRsp& from);
  void MergeFrom(const Proto_STLMailListRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_email.Proto_CSMailListRsp cs_rsp = 2;
  inline bool has_cs_rsp() const;
  inline void clear_cs_rsp();
  static const int kCsRspFieldNumber = 2;
  inline const ::proto_email::Proto_CSMailListRsp& cs_rsp() const;
  inline ::proto_email::Proto_CSMailListRsp* mutable_cs_rsp();
  inline ::proto_email::Proto_CSMailListRsp* release_cs_rsp();
  inline void set_allocated_cs_rsp(::proto_email::Proto_CSMailListRsp* cs_rsp);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STLMailListRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_cs_rsp();
  inline void clear_has_cs_rsp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_email::Proto_CSMailListRsp* cs_rsp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STLMailListRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_LTSMailReadReq : public ::google::protobuf::Message {
 public:
  Proto_LTSMailReadReq();
  virtual ~Proto_LTSMailReadReq();

  Proto_LTSMailReadReq(const Proto_LTSMailReadReq& from);

  inline Proto_LTSMailReadReq& operator=(const Proto_LTSMailReadReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_LTSMailReadReq& default_instance();

  void Swap(Proto_LTSMailReadReq* other);

  // implements Message ----------------------------------------------

  Proto_LTSMailReadReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_LTSMailReadReq& from);
  void MergeFrom(const Proto_LTSMailReadReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional uint64 mail_id = 2;
  inline bool has_mail_id() const;
  inline void clear_mail_id();
  static const int kMailIdFieldNumber = 2;
  inline ::google::protobuf::uint64 mail_id() const;
  inline void set_mail_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_LTSMailReadReq)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_mail_id();
  inline void clear_has_mail_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::uint64 mail_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_LTSMailReadReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STLMailReadRsp : public ::google::protobuf::Message {
 public:
  Proto_STLMailReadRsp();
  virtual ~Proto_STLMailReadRsp();

  Proto_STLMailReadRsp(const Proto_STLMailReadRsp& from);

  inline Proto_STLMailReadRsp& operator=(const Proto_STLMailReadRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STLMailReadRsp& default_instance();

  void Swap(Proto_STLMailReadRsp* other);

  // implements Message ----------------------------------------------

  Proto_STLMailReadRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STLMailReadRsp& from);
  void MergeFrom(const Proto_STLMailReadRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_email.Proto_CSMailReadRsp cs_rsp = 2;
  inline bool has_cs_rsp() const;
  inline void clear_cs_rsp();
  static const int kCsRspFieldNumber = 2;
  inline const ::proto_email::Proto_CSMailReadRsp& cs_rsp() const;
  inline ::proto_email::Proto_CSMailReadRsp* mutable_cs_rsp();
  inline ::proto_email::Proto_CSMailReadRsp* release_cs_rsp();
  inline void set_allocated_cs_rsp(::proto_email::Proto_CSMailReadRsp* cs_rsp);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STLMailReadRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_cs_rsp();
  inline void clear_has_cs_rsp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_email::Proto_CSMailReadRsp* cs_rsp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STLMailReadRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STLMailAutoPushRsp : public ::google::protobuf::Message {
 public:
  Proto_STLMailAutoPushRsp();
  virtual ~Proto_STLMailAutoPushRsp();

  Proto_STLMailAutoPushRsp(const Proto_STLMailAutoPushRsp& from);

  inline Proto_STLMailAutoPushRsp& operator=(const Proto_STLMailAutoPushRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STLMailAutoPushRsp& default_instance();

  void Swap(Proto_STLMailAutoPushRsp* other);

  // implements Message ----------------------------------------------

  Proto_STLMailAutoPushRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STLMailAutoPushRsp& from);
  void MergeFrom(const Proto_STLMailAutoPushRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // repeated .proto_email.UserMailData role_mail_list = 2;
  inline int role_mail_list_size() const;
  inline void clear_role_mail_list();
  static const int kRoleMailListFieldNumber = 2;
  inline const ::proto_email::UserMailData& role_mail_list(int index) const;
  inline ::proto_email::UserMailData* mutable_role_mail_list(int index);
  inline ::proto_email::UserMailData* add_role_mail_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >&
      role_mail_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >*
      mutable_role_mail_list();

  // optional int32 all_count = 3;
  inline bool has_all_count() const;
  inline void clear_all_count();
  static const int kAllCountFieldNumber = 3;
  inline ::google::protobuf::int32 all_count() const;
  inline void set_all_count(::google::protobuf::int32 value);

  // optional int32 no_read_count = 4;
  inline bool has_no_read_count() const;
  inline void clear_no_read_count();
  static const int kNoReadCountFieldNumber = 4;
  inline ::google::protobuf::int32 no_read_count() const;
  inline void set_no_read_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STLMailAutoPushRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_all_count();
  inline void clear_has_all_count();
  inline void set_has_no_read_count();
  inline void clear_has_no_read_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData > role_mail_list_;
  ::google::protobuf::int32 all_count_;
  ::google::protobuf::int32 no_read_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STLMailAutoPushRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_LTSMailDelReq : public ::google::protobuf::Message {
 public:
  Proto_LTSMailDelReq();
  virtual ~Proto_LTSMailDelReq();

  Proto_LTSMailDelReq(const Proto_LTSMailDelReq& from);

  inline Proto_LTSMailDelReq& operator=(const Proto_LTSMailDelReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_LTSMailDelReq& default_instance();

  void Swap(Proto_LTSMailDelReq* other);

  // implements Message ----------------------------------------------

  Proto_LTSMailDelReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_LTSMailDelReq& from);
  void MergeFrom(const Proto_LTSMailDelReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_email.Proto_CSMailDelReq cs_req = 2;
  inline bool has_cs_req() const;
  inline void clear_cs_req();
  static const int kCsReqFieldNumber = 2;
  inline const ::proto_email::Proto_CSMailDelReq& cs_req() const;
  inline ::proto_email::Proto_CSMailDelReq* mutable_cs_req();
  inline ::proto_email::Proto_CSMailDelReq* release_cs_req();
  inline void set_allocated_cs_req(::proto_email::Proto_CSMailDelReq* cs_req);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_LTSMailDelReq)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_cs_req();
  inline void clear_has_cs_req();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_email::Proto_CSMailDelReq* cs_req_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_LTSMailDelReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STLMailDelRsp : public ::google::protobuf::Message {
 public:
  Proto_STLMailDelRsp();
  virtual ~Proto_STLMailDelRsp();

  Proto_STLMailDelRsp(const Proto_STLMailDelRsp& from);

  inline Proto_STLMailDelRsp& operator=(const Proto_STLMailDelRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STLMailDelRsp& default_instance();

  void Swap(Proto_STLMailDelRsp* other);

  // implements Message ----------------------------------------------

  Proto_STLMailDelRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STLMailDelRsp& from);
  void MergeFrom(const Proto_STLMailDelRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_email.Proto_CSMailDelRsp cs_rsp = 2;
  inline bool has_cs_rsp() const;
  inline void clear_cs_rsp();
  static const int kCsRspFieldNumber = 2;
  inline const ::proto_email::Proto_CSMailDelRsp& cs_rsp() const;
  inline ::proto_email::Proto_CSMailDelRsp* mutable_cs_rsp();
  inline ::proto_email::Proto_CSMailDelRsp* release_cs_rsp();
  inline void set_allocated_cs_rsp(::proto_email::Proto_CSMailDelRsp* cs_rsp);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STLMailDelRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_cs_rsp();
  inline void clear_has_cs_rsp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_email::Proto_CSMailDelRsp* cs_rsp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STLMailDelRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_OtherTSMailCreateReq : public ::google::protobuf::Message {
 public:
  Proto_OtherTSMailCreateReq();
  virtual ~Proto_OtherTSMailCreateReq();

  Proto_OtherTSMailCreateReq(const Proto_OtherTSMailCreateReq& from);

  inline Proto_OtherTSMailCreateReq& operator=(const Proto_OtherTSMailCreateReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_OtherTSMailCreateReq& default_instance();

  void Swap(Proto_OtherTSMailCreateReq* other);

  // implements Message ----------------------------------------------

  Proto_OtherTSMailCreateReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_OtherTSMailCreateReq& from);
  void MergeFrom(const Proto_OtherTSMailCreateReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_ff.tbUserMailDetail role_mail = 2;
  inline bool has_role_mail() const;
  inline void clear_role_mail();
  static const int kRoleMailFieldNumber = 2;
  inline const ::proto_ff::tbUserMailDetail& role_mail() const;
  inline ::proto_ff::tbUserMailDetail* mutable_role_mail();
  inline ::proto_ff::tbUserMailDetail* release_role_mail();
  inline void set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_OtherTSMailCreateReq)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_role_mail();
  inline void clear_has_role_mail();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_ff::tbUserMailDetail* role_mail_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_OtherTSMailCreateReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STOtherMailCreateRsp : public ::google::protobuf::Message {
 public:
  Proto_STOtherMailCreateRsp();
  virtual ~Proto_STOtherMailCreateRsp();

  Proto_STOtherMailCreateRsp(const Proto_STOtherMailCreateRsp& from);

  inline Proto_STOtherMailCreateRsp& operator=(const Proto_STOtherMailCreateRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STOtherMailCreateRsp& default_instance();

  void Swap(Proto_STOtherMailCreateRsp* other);

  // implements Message ----------------------------------------------

  Proto_STOtherMailCreateRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STOtherMailCreateRsp& from);
  void MergeFrom(const Proto_STOtherMailCreateRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_ff.tbUserMailDetail role_mail = 2;
  inline bool has_role_mail() const;
  inline void clear_role_mail();
  static const int kRoleMailFieldNumber = 2;
  inline const ::proto_ff::tbUserMailDetail& role_mail() const;
  inline ::proto_ff::tbUserMailDetail* mutable_role_mail();
  inline ::proto_ff::tbUserMailDetail* release_role_mail();
  inline void set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail);

  // optional int32 result = 3;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 3;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STOtherMailCreateRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_role_mail();
  inline void clear_has_role_mail();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_ff::tbUserMailDetail* role_mail_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STOtherMailCreateRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_LTSMailGetItemReq : public ::google::protobuf::Message {
 public:
  Proto_LTSMailGetItemReq();
  virtual ~Proto_LTSMailGetItemReq();

  Proto_LTSMailGetItemReq(const Proto_LTSMailGetItemReq& from);

  inline Proto_LTSMailGetItemReq& operator=(const Proto_LTSMailGetItemReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_LTSMailGetItemReq& default_instance();

  void Swap(Proto_LTSMailGetItemReq* other);

  // implements Message ----------------------------------------------

  Proto_LTSMailGetItemReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_LTSMailGetItemReq& from);
  void MergeFrom(const Proto_LTSMailGetItemReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional uint64 mail_id = 2;
  inline bool has_mail_id() const;
  inline void clear_mail_id();
  static const int kMailIdFieldNumber = 2;
  inline ::google::protobuf::uint64 mail_id() const;
  inline void set_mail_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_LTSMailGetItemReq)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_mail_id();
  inline void clear_has_mail_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::uint64 mail_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_LTSMailGetItemReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STLMailGetItemRsp : public ::google::protobuf::Message {
 public:
  Proto_STLMailGetItemRsp();
  virtual ~Proto_STLMailGetItemRsp();

  Proto_STLMailGetItemRsp(const Proto_STLMailGetItemRsp& from);

  inline Proto_STLMailGetItemRsp& operator=(const Proto_STLMailGetItemRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STLMailGetItemRsp& default_instance();

  void Swap(Proto_STLMailGetItemRsp* other);

  // implements Message ----------------------------------------------

  Proto_STLMailGetItemRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STLMailGetItemRsp& from);
  void MergeFrom(const Proto_STLMailGetItemRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_email.Proto_CSMailGetItemRsp cs_rsp = 2;
  inline bool has_cs_rsp() const;
  inline void clear_cs_rsp();
  static const int kCsRspFieldNumber = 2;
  inline const ::proto_email::Proto_CSMailGetItemRsp& cs_rsp() const;
  inline ::proto_email::Proto_CSMailGetItemRsp* mutable_cs_rsp();
  inline ::proto_email::Proto_CSMailGetItemRsp* release_cs_rsp();
  inline void set_allocated_cs_rsp(::proto_email::Proto_CSMailGetItemRsp* cs_rsp);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STLMailGetItemRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_cs_rsp();
  inline void clear_has_cs_rsp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_email::Proto_CSMailGetItemRsp* cs_rsp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STLMailGetItemRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_STLMailReadItemReq : public ::google::protobuf::Message {
 public:
  Proto_STLMailReadItemReq();
  virtual ~Proto_STLMailReadItemReq();

  Proto_STLMailReadItemReq(const Proto_STLMailReadItemReq& from);

  inline Proto_STLMailReadItemReq& operator=(const Proto_STLMailReadItemReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STLMailReadItemReq& default_instance();

  void Swap(Proto_STLMailReadItemReq* other);

  // implements Message ----------------------------------------------

  Proto_STLMailReadItemReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STLMailReadItemReq& from);
  void MergeFrom(const Proto_STLMailReadItemReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // repeated .proto_email.MailItem item_list = 2;
  inline int item_list_size() const;
  inline void clear_item_list();
  static const int kItemListFieldNumber = 2;
  inline const ::proto_email::MailItem& item_list(int index) const;
  inline ::proto_email::MailItem* mutable_item_list(int index);
  inline ::proto_email::MailItem* add_item_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
      item_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
      mutable_item_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STLMailReadItemReq)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem > item_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_STLMailReadItemReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_LTSMailReadItemRsp : public ::google::protobuf::Message {
 public:
  Proto_LTSMailReadItemRsp();
  virtual ~Proto_LTSMailReadItemRsp();

  Proto_LTSMailReadItemRsp(const Proto_LTSMailReadItemRsp& from);

  inline Proto_LTSMailReadItemRsp& operator=(const Proto_LTSMailReadItemRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_LTSMailReadItemRsp& default_instance();

  void Swap(Proto_LTSMailReadItemRsp* other);

  // implements Message ----------------------------------------------

  Proto_LTSMailReadItemRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_LTSMailReadItemRsp& from);
  void MergeFrom(const Proto_LTSMailReadItemRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // repeated .proto_email.MailItem get_id = 4;
  inline int get_id_size() const;
  inline void clear_get_id();
  static const int kGetIdFieldNumber = 4;
  inline const ::proto_email::MailItem& get_id(int index) const;
  inline ::proto_email::MailItem* mutable_get_id(int index);
  inline ::proto_email::MailItem* add_get_id();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
      get_id() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
      mutable_get_id();

  // repeated .proto_email.MailItem id = 5;
  inline int id_size() const;
  inline void clear_id();
  static const int kIdFieldNumber = 5;
  inline const ::proto_email::MailItem& id(int index) const;
  inline ::proto_email::MailItem* mutable_id(int index);
  inline ::proto_email::MailItem* add_id();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
      id() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
      mutable_id();

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_LTSMailReadItemRsp)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem > get_id_;
  ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem > id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_LTSMailReadItemRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// Proto_GSMailCreateReq

// optional uint64 role_id = 1;
inline bool Proto_GSMailCreateReq::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_GSMailCreateReq::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_GSMailCreateReq::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_GSMailCreateReq::clear_role_id() {
  role_id_ = GOOGLE_ULONGLONG(0);
  clear_has_role_id();
}
inline ::google::protobuf::uint64 Proto_GSMailCreateReq::role_id() const {
  return role_id_;
}
inline void Proto_GSMailCreateReq::set_role_id(::google::protobuf::uint64 value) {
  set_has_role_id();
  role_id_ = value;
}

// optional .proto_ff.tbUserMailDetail role_mail = 2;
inline bool Proto_GSMailCreateReq::has_role_mail() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_GSMailCreateReq::set_has_role_mail() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_GSMailCreateReq::clear_has_role_mail() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_GSMailCreateReq::clear_role_mail() {
  if (role_mail_ != NULL) role_mail_->::proto_ff::tbUserMailDetail::Clear();
  clear_has_role_mail();
}
inline const ::proto_ff::tbUserMailDetail& Proto_GSMailCreateReq::role_mail() const {
  return role_mail_ != NULL ? *role_mail_ : *default_instance_->role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_GSMailCreateReq::mutable_role_mail() {
  set_has_role_mail();
  if (role_mail_ == NULL) role_mail_ = new ::proto_ff::tbUserMailDetail;
  return role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_GSMailCreateReq::release_role_mail() {
  clear_has_role_mail();
  ::proto_ff::tbUserMailDetail* temp = role_mail_;
  role_mail_ = NULL;
  return temp;
}
inline void Proto_GSMailCreateReq::set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail) {
  delete role_mail_;
  role_mail_ = role_mail;
  if (role_mail) {
    set_has_role_mail();
  } else {
    clear_has_role_mail();
  }
}

// -------------------------------------------------------------------

// Proto_SGMailCreateRsp

// optional uint64 role_id = 1;
inline bool Proto_SGMailCreateRsp::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_SGMailCreateRsp::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_SGMailCreateRsp::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_SGMailCreateRsp::clear_role_id() {
  role_id_ = GOOGLE_ULONGLONG(0);
  clear_has_role_id();
}
inline ::google::protobuf::uint64 Proto_SGMailCreateRsp::role_id() const {
  return role_id_;
}
inline void Proto_SGMailCreateRsp::set_role_id(::google::protobuf::uint64 value) {
  set_has_role_id();
  role_id_ = value;
}

// optional .proto_ff.tbUserMailDetail role_mail = 2;
inline bool Proto_SGMailCreateRsp::has_role_mail() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_SGMailCreateRsp::set_has_role_mail() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_SGMailCreateRsp::clear_has_role_mail() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_SGMailCreateRsp::clear_role_mail() {
  if (role_mail_ != NULL) role_mail_->::proto_ff::tbUserMailDetail::Clear();
  clear_has_role_mail();
}
inline const ::proto_ff::tbUserMailDetail& Proto_SGMailCreateRsp::role_mail() const {
  return role_mail_ != NULL ? *role_mail_ : *default_instance_->role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_SGMailCreateRsp::mutable_role_mail() {
  set_has_role_mail();
  if (role_mail_ == NULL) role_mail_ = new ::proto_ff::tbUserMailDetail;
  return role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_SGMailCreateRsp::release_role_mail() {
  clear_has_role_mail();
  ::proto_ff::tbUserMailDetail* temp = role_mail_;
  role_mail_ = NULL;
  return temp;
}
inline void Proto_SGMailCreateRsp::set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail) {
  delete role_mail_;
  role_mail_ = role_mail;
  if (role_mail) {
    set_has_role_mail();
  } else {
    clear_has_role_mail();
  }
}

// optional int32 result = 3;
inline bool Proto_SGMailCreateRsp::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto_SGMailCreateRsp::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto_SGMailCreateRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto_SGMailCreateRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 Proto_SGMailCreateRsp::result() const {
  return result_;
}
inline void Proto_SGMailCreateRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// Proto_LTSMailListReq

// optional uint64 user_id = 1;
inline bool Proto_LTSMailListReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_LTSMailListReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_LTSMailListReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_LTSMailListReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailListReq::user_id() const {
  return user_id_;
}
inline void Proto_LTSMailListReq::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_email.Proto_CSMailListReq cs_req = 2;
inline bool Proto_LTSMailListReq::has_cs_req() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_LTSMailListReq::set_has_cs_req() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_LTSMailListReq::clear_has_cs_req() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_LTSMailListReq::clear_cs_req() {
  if (cs_req_ != NULL) cs_req_->::proto_email::Proto_CSMailListReq::Clear();
  clear_has_cs_req();
}
inline const ::proto_email::Proto_CSMailListReq& Proto_LTSMailListReq::cs_req() const {
  return cs_req_ != NULL ? *cs_req_ : *default_instance_->cs_req_;
}
inline ::proto_email::Proto_CSMailListReq* Proto_LTSMailListReq::mutable_cs_req() {
  set_has_cs_req();
  if (cs_req_ == NULL) cs_req_ = new ::proto_email::Proto_CSMailListReq;
  return cs_req_;
}
inline ::proto_email::Proto_CSMailListReq* Proto_LTSMailListReq::release_cs_req() {
  clear_has_cs_req();
  ::proto_email::Proto_CSMailListReq* temp = cs_req_;
  cs_req_ = NULL;
  return temp;
}
inline void Proto_LTSMailListReq::set_allocated_cs_req(::proto_email::Proto_CSMailListReq* cs_req) {
  delete cs_req_;
  cs_req_ = cs_req;
  if (cs_req) {
    set_has_cs_req();
  } else {
    clear_has_cs_req();
  }
}

// -------------------------------------------------------------------

// Proto_STLMailListRsp

// optional uint64 user_id = 1;
inline bool Proto_STLMailListRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STLMailListRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STLMailListRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STLMailListRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STLMailListRsp::user_id() const {
  return user_id_;
}
inline void Proto_STLMailListRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_email.Proto_CSMailListRsp cs_rsp = 2;
inline bool Proto_STLMailListRsp::has_cs_rsp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_STLMailListRsp::set_has_cs_rsp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_STLMailListRsp::clear_has_cs_rsp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_STLMailListRsp::clear_cs_rsp() {
  if (cs_rsp_ != NULL) cs_rsp_->::proto_email::Proto_CSMailListRsp::Clear();
  clear_has_cs_rsp();
}
inline const ::proto_email::Proto_CSMailListRsp& Proto_STLMailListRsp::cs_rsp() const {
  return cs_rsp_ != NULL ? *cs_rsp_ : *default_instance_->cs_rsp_;
}
inline ::proto_email::Proto_CSMailListRsp* Proto_STLMailListRsp::mutable_cs_rsp() {
  set_has_cs_rsp();
  if (cs_rsp_ == NULL) cs_rsp_ = new ::proto_email::Proto_CSMailListRsp;
  return cs_rsp_;
}
inline ::proto_email::Proto_CSMailListRsp* Proto_STLMailListRsp::release_cs_rsp() {
  clear_has_cs_rsp();
  ::proto_email::Proto_CSMailListRsp* temp = cs_rsp_;
  cs_rsp_ = NULL;
  return temp;
}
inline void Proto_STLMailListRsp::set_allocated_cs_rsp(::proto_email::Proto_CSMailListRsp* cs_rsp) {
  delete cs_rsp_;
  cs_rsp_ = cs_rsp;
  if (cs_rsp) {
    set_has_cs_rsp();
  } else {
    clear_has_cs_rsp();
  }
}

// -------------------------------------------------------------------

// Proto_LTSMailReadReq

// optional uint64 user_id = 1;
inline bool Proto_LTSMailReadReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_LTSMailReadReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_LTSMailReadReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_LTSMailReadReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailReadReq::user_id() const {
  return user_id_;
}
inline void Proto_LTSMailReadReq::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional uint64 mail_id = 2;
inline bool Proto_LTSMailReadReq::has_mail_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_LTSMailReadReq::set_has_mail_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_LTSMailReadReq::clear_has_mail_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_LTSMailReadReq::clear_mail_id() {
  mail_id_ = GOOGLE_ULONGLONG(0);
  clear_has_mail_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailReadReq::mail_id() const {
  return mail_id_;
}
inline void Proto_LTSMailReadReq::set_mail_id(::google::protobuf::uint64 value) {
  set_has_mail_id();
  mail_id_ = value;
}

// -------------------------------------------------------------------

// Proto_STLMailReadRsp

// optional uint64 user_id = 1;
inline bool Proto_STLMailReadRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STLMailReadRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STLMailReadRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STLMailReadRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STLMailReadRsp::user_id() const {
  return user_id_;
}
inline void Proto_STLMailReadRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_email.Proto_CSMailReadRsp cs_rsp = 2;
inline bool Proto_STLMailReadRsp::has_cs_rsp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_STLMailReadRsp::set_has_cs_rsp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_STLMailReadRsp::clear_has_cs_rsp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_STLMailReadRsp::clear_cs_rsp() {
  if (cs_rsp_ != NULL) cs_rsp_->::proto_email::Proto_CSMailReadRsp::Clear();
  clear_has_cs_rsp();
}
inline const ::proto_email::Proto_CSMailReadRsp& Proto_STLMailReadRsp::cs_rsp() const {
  return cs_rsp_ != NULL ? *cs_rsp_ : *default_instance_->cs_rsp_;
}
inline ::proto_email::Proto_CSMailReadRsp* Proto_STLMailReadRsp::mutable_cs_rsp() {
  set_has_cs_rsp();
  if (cs_rsp_ == NULL) cs_rsp_ = new ::proto_email::Proto_CSMailReadRsp;
  return cs_rsp_;
}
inline ::proto_email::Proto_CSMailReadRsp* Proto_STLMailReadRsp::release_cs_rsp() {
  clear_has_cs_rsp();
  ::proto_email::Proto_CSMailReadRsp* temp = cs_rsp_;
  cs_rsp_ = NULL;
  return temp;
}
inline void Proto_STLMailReadRsp::set_allocated_cs_rsp(::proto_email::Proto_CSMailReadRsp* cs_rsp) {
  delete cs_rsp_;
  cs_rsp_ = cs_rsp;
  if (cs_rsp) {
    set_has_cs_rsp();
  } else {
    clear_has_cs_rsp();
  }
}

// -------------------------------------------------------------------

// Proto_STLMailAutoPushRsp

// optional uint64 user_id = 1;
inline bool Proto_STLMailAutoPushRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STLMailAutoPushRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STLMailAutoPushRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STLMailAutoPushRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STLMailAutoPushRsp::user_id() const {
  return user_id_;
}
inline void Proto_STLMailAutoPushRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .proto_email.UserMailData role_mail_list = 2;
inline int Proto_STLMailAutoPushRsp::role_mail_list_size() const {
  return role_mail_list_.size();
}
inline void Proto_STLMailAutoPushRsp::clear_role_mail_list() {
  role_mail_list_.Clear();
}
inline const ::proto_email::UserMailData& Proto_STLMailAutoPushRsp::role_mail_list(int index) const {
  return role_mail_list_.Get(index);
}
inline ::proto_email::UserMailData* Proto_STLMailAutoPushRsp::mutable_role_mail_list(int index) {
  return role_mail_list_.Mutable(index);
}
inline ::proto_email::UserMailData* Proto_STLMailAutoPushRsp::add_role_mail_list() {
  return role_mail_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >&
Proto_STLMailAutoPushRsp::role_mail_list() const {
  return role_mail_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >*
Proto_STLMailAutoPushRsp::mutable_role_mail_list() {
  return &role_mail_list_;
}

// optional int32 all_count = 3;
inline bool Proto_STLMailAutoPushRsp::has_all_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto_STLMailAutoPushRsp::set_has_all_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto_STLMailAutoPushRsp::clear_has_all_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto_STLMailAutoPushRsp::clear_all_count() {
  all_count_ = 0;
  clear_has_all_count();
}
inline ::google::protobuf::int32 Proto_STLMailAutoPushRsp::all_count() const {
  return all_count_;
}
inline void Proto_STLMailAutoPushRsp::set_all_count(::google::protobuf::int32 value) {
  set_has_all_count();
  all_count_ = value;
}

// optional int32 no_read_count = 4;
inline bool Proto_STLMailAutoPushRsp::has_no_read_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto_STLMailAutoPushRsp::set_has_no_read_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto_STLMailAutoPushRsp::clear_has_no_read_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto_STLMailAutoPushRsp::clear_no_read_count() {
  no_read_count_ = 0;
  clear_has_no_read_count();
}
inline ::google::protobuf::int32 Proto_STLMailAutoPushRsp::no_read_count() const {
  return no_read_count_;
}
inline void Proto_STLMailAutoPushRsp::set_no_read_count(::google::protobuf::int32 value) {
  set_has_no_read_count();
  no_read_count_ = value;
}

// -------------------------------------------------------------------

// Proto_LTSMailDelReq

// optional uint64 user_id = 1;
inline bool Proto_LTSMailDelReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_LTSMailDelReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_LTSMailDelReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_LTSMailDelReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailDelReq::user_id() const {
  return user_id_;
}
inline void Proto_LTSMailDelReq::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_email.Proto_CSMailDelReq cs_req = 2;
inline bool Proto_LTSMailDelReq::has_cs_req() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_LTSMailDelReq::set_has_cs_req() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_LTSMailDelReq::clear_has_cs_req() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_LTSMailDelReq::clear_cs_req() {
  if (cs_req_ != NULL) cs_req_->::proto_email::Proto_CSMailDelReq::Clear();
  clear_has_cs_req();
}
inline const ::proto_email::Proto_CSMailDelReq& Proto_LTSMailDelReq::cs_req() const {
  return cs_req_ != NULL ? *cs_req_ : *default_instance_->cs_req_;
}
inline ::proto_email::Proto_CSMailDelReq* Proto_LTSMailDelReq::mutable_cs_req() {
  set_has_cs_req();
  if (cs_req_ == NULL) cs_req_ = new ::proto_email::Proto_CSMailDelReq;
  return cs_req_;
}
inline ::proto_email::Proto_CSMailDelReq* Proto_LTSMailDelReq::release_cs_req() {
  clear_has_cs_req();
  ::proto_email::Proto_CSMailDelReq* temp = cs_req_;
  cs_req_ = NULL;
  return temp;
}
inline void Proto_LTSMailDelReq::set_allocated_cs_req(::proto_email::Proto_CSMailDelReq* cs_req) {
  delete cs_req_;
  cs_req_ = cs_req;
  if (cs_req) {
    set_has_cs_req();
  } else {
    clear_has_cs_req();
  }
}

// -------------------------------------------------------------------

// Proto_STLMailDelRsp

// optional uint64 user_id = 1;
inline bool Proto_STLMailDelRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STLMailDelRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STLMailDelRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STLMailDelRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STLMailDelRsp::user_id() const {
  return user_id_;
}
inline void Proto_STLMailDelRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_email.Proto_CSMailDelRsp cs_rsp = 2;
inline bool Proto_STLMailDelRsp::has_cs_rsp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_STLMailDelRsp::set_has_cs_rsp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_STLMailDelRsp::clear_has_cs_rsp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_STLMailDelRsp::clear_cs_rsp() {
  if (cs_rsp_ != NULL) cs_rsp_->::proto_email::Proto_CSMailDelRsp::Clear();
  clear_has_cs_rsp();
}
inline const ::proto_email::Proto_CSMailDelRsp& Proto_STLMailDelRsp::cs_rsp() const {
  return cs_rsp_ != NULL ? *cs_rsp_ : *default_instance_->cs_rsp_;
}
inline ::proto_email::Proto_CSMailDelRsp* Proto_STLMailDelRsp::mutable_cs_rsp() {
  set_has_cs_rsp();
  if (cs_rsp_ == NULL) cs_rsp_ = new ::proto_email::Proto_CSMailDelRsp;
  return cs_rsp_;
}
inline ::proto_email::Proto_CSMailDelRsp* Proto_STLMailDelRsp::release_cs_rsp() {
  clear_has_cs_rsp();
  ::proto_email::Proto_CSMailDelRsp* temp = cs_rsp_;
  cs_rsp_ = NULL;
  return temp;
}
inline void Proto_STLMailDelRsp::set_allocated_cs_rsp(::proto_email::Proto_CSMailDelRsp* cs_rsp) {
  delete cs_rsp_;
  cs_rsp_ = cs_rsp;
  if (cs_rsp) {
    set_has_cs_rsp();
  } else {
    clear_has_cs_rsp();
  }
}

// -------------------------------------------------------------------

// Proto_OtherTSMailCreateReq

// optional uint64 user_id = 1;
inline bool Proto_OtherTSMailCreateReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_OtherTSMailCreateReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_OtherTSMailCreateReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_OtherTSMailCreateReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_OtherTSMailCreateReq::user_id() const {
  return user_id_;
}
inline void Proto_OtherTSMailCreateReq::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_ff.tbUserMailDetail role_mail = 2;
inline bool Proto_OtherTSMailCreateReq::has_role_mail() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_OtherTSMailCreateReq::set_has_role_mail() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_OtherTSMailCreateReq::clear_has_role_mail() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_OtherTSMailCreateReq::clear_role_mail() {
  if (role_mail_ != NULL) role_mail_->::proto_ff::tbUserMailDetail::Clear();
  clear_has_role_mail();
}
inline const ::proto_ff::tbUserMailDetail& Proto_OtherTSMailCreateReq::role_mail() const {
  return role_mail_ != NULL ? *role_mail_ : *default_instance_->role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_OtherTSMailCreateReq::mutable_role_mail() {
  set_has_role_mail();
  if (role_mail_ == NULL) role_mail_ = new ::proto_ff::tbUserMailDetail;
  return role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_OtherTSMailCreateReq::release_role_mail() {
  clear_has_role_mail();
  ::proto_ff::tbUserMailDetail* temp = role_mail_;
  role_mail_ = NULL;
  return temp;
}
inline void Proto_OtherTSMailCreateReq::set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail) {
  delete role_mail_;
  role_mail_ = role_mail;
  if (role_mail) {
    set_has_role_mail();
  } else {
    clear_has_role_mail();
  }
}

// -------------------------------------------------------------------

// Proto_STOtherMailCreateRsp

// optional uint64 user_id = 1;
inline bool Proto_STOtherMailCreateRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STOtherMailCreateRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STOtherMailCreateRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STOtherMailCreateRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STOtherMailCreateRsp::user_id() const {
  return user_id_;
}
inline void Proto_STOtherMailCreateRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_ff.tbUserMailDetail role_mail = 2;
inline bool Proto_STOtherMailCreateRsp::has_role_mail() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_STOtherMailCreateRsp::set_has_role_mail() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_STOtherMailCreateRsp::clear_has_role_mail() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_STOtherMailCreateRsp::clear_role_mail() {
  if (role_mail_ != NULL) role_mail_->::proto_ff::tbUserMailDetail::Clear();
  clear_has_role_mail();
}
inline const ::proto_ff::tbUserMailDetail& Proto_STOtherMailCreateRsp::role_mail() const {
  return role_mail_ != NULL ? *role_mail_ : *default_instance_->role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_STOtherMailCreateRsp::mutable_role_mail() {
  set_has_role_mail();
  if (role_mail_ == NULL) role_mail_ = new ::proto_ff::tbUserMailDetail;
  return role_mail_;
}
inline ::proto_ff::tbUserMailDetail* Proto_STOtherMailCreateRsp::release_role_mail() {
  clear_has_role_mail();
  ::proto_ff::tbUserMailDetail* temp = role_mail_;
  role_mail_ = NULL;
  return temp;
}
inline void Proto_STOtherMailCreateRsp::set_allocated_role_mail(::proto_ff::tbUserMailDetail* role_mail) {
  delete role_mail_;
  role_mail_ = role_mail;
  if (role_mail) {
    set_has_role_mail();
  } else {
    clear_has_role_mail();
  }
}

// optional int32 result = 3;
inline bool Proto_STOtherMailCreateRsp::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto_STOtherMailCreateRsp::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto_STOtherMailCreateRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto_STOtherMailCreateRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 Proto_STOtherMailCreateRsp::result() const {
  return result_;
}
inline void Proto_STOtherMailCreateRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// Proto_LTSMailGetItemReq

// optional uint64 user_id = 1;
inline bool Proto_LTSMailGetItemReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_LTSMailGetItemReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_LTSMailGetItemReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_LTSMailGetItemReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailGetItemReq::user_id() const {
  return user_id_;
}
inline void Proto_LTSMailGetItemReq::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional uint64 mail_id = 2;
inline bool Proto_LTSMailGetItemReq::has_mail_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_LTSMailGetItemReq::set_has_mail_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_LTSMailGetItemReq::clear_has_mail_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_LTSMailGetItemReq::clear_mail_id() {
  mail_id_ = GOOGLE_ULONGLONG(0);
  clear_has_mail_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailGetItemReq::mail_id() const {
  return mail_id_;
}
inline void Proto_LTSMailGetItemReq::set_mail_id(::google::protobuf::uint64 value) {
  set_has_mail_id();
  mail_id_ = value;
}

// -------------------------------------------------------------------

// Proto_STLMailGetItemRsp

// optional uint64 user_id = 1;
inline bool Proto_STLMailGetItemRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STLMailGetItemRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STLMailGetItemRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STLMailGetItemRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STLMailGetItemRsp::user_id() const {
  return user_id_;
}
inline void Proto_STLMailGetItemRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_email.Proto_CSMailGetItemRsp cs_rsp = 2;
inline bool Proto_STLMailGetItemRsp::has_cs_rsp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_STLMailGetItemRsp::set_has_cs_rsp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_STLMailGetItemRsp::clear_has_cs_rsp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_STLMailGetItemRsp::clear_cs_rsp() {
  if (cs_rsp_ != NULL) cs_rsp_->::proto_email::Proto_CSMailGetItemRsp::Clear();
  clear_has_cs_rsp();
}
inline const ::proto_email::Proto_CSMailGetItemRsp& Proto_STLMailGetItemRsp::cs_rsp() const {
  return cs_rsp_ != NULL ? *cs_rsp_ : *default_instance_->cs_rsp_;
}
inline ::proto_email::Proto_CSMailGetItemRsp* Proto_STLMailGetItemRsp::mutable_cs_rsp() {
  set_has_cs_rsp();
  if (cs_rsp_ == NULL) cs_rsp_ = new ::proto_email::Proto_CSMailGetItemRsp;
  return cs_rsp_;
}
inline ::proto_email::Proto_CSMailGetItemRsp* Proto_STLMailGetItemRsp::release_cs_rsp() {
  clear_has_cs_rsp();
  ::proto_email::Proto_CSMailGetItemRsp* temp = cs_rsp_;
  cs_rsp_ = NULL;
  return temp;
}
inline void Proto_STLMailGetItemRsp::set_allocated_cs_rsp(::proto_email::Proto_CSMailGetItemRsp* cs_rsp) {
  delete cs_rsp_;
  cs_rsp_ = cs_rsp;
  if (cs_rsp) {
    set_has_cs_rsp();
  } else {
    clear_has_cs_rsp();
  }
}

// -------------------------------------------------------------------

// Proto_STLMailReadItemReq

// optional uint64 user_id = 1;
inline bool Proto_STLMailReadItemReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STLMailReadItemReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STLMailReadItemReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STLMailReadItemReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STLMailReadItemReq::user_id() const {
  return user_id_;
}
inline void Proto_STLMailReadItemReq::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .proto_email.MailItem item_list = 2;
inline int Proto_STLMailReadItemReq::item_list_size() const {
  return item_list_.size();
}
inline void Proto_STLMailReadItemReq::clear_item_list() {
  item_list_.Clear();
}
inline const ::proto_email::MailItem& Proto_STLMailReadItemReq::item_list(int index) const {
  return item_list_.Get(index);
}
inline ::proto_email::MailItem* Proto_STLMailReadItemReq::mutable_item_list(int index) {
  return item_list_.Mutable(index);
}
inline ::proto_email::MailItem* Proto_STLMailReadItemReq::add_item_list() {
  return item_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
Proto_STLMailReadItemReq::item_list() const {
  return item_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
Proto_STLMailReadItemReq::mutable_item_list() {
  return &item_list_;
}

// -------------------------------------------------------------------

// Proto_LTSMailReadItemRsp

// optional uint64 user_id = 1;
inline bool Proto_LTSMailReadItemRsp::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_LTSMailReadItemRsp::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_LTSMailReadItemRsp::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_LTSMailReadItemRsp::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_LTSMailReadItemRsp::user_id() const {
  return user_id_;
}
inline void Proto_LTSMailReadItemRsp::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .proto_email.MailItem get_id = 4;
inline int Proto_LTSMailReadItemRsp::get_id_size() const {
  return get_id_.size();
}
inline void Proto_LTSMailReadItemRsp::clear_get_id() {
  get_id_.Clear();
}
inline const ::proto_email::MailItem& Proto_LTSMailReadItemRsp::get_id(int index) const {
  return get_id_.Get(index);
}
inline ::proto_email::MailItem* Proto_LTSMailReadItemRsp::mutable_get_id(int index) {
  return get_id_.Mutable(index);
}
inline ::proto_email::MailItem* Proto_LTSMailReadItemRsp::add_get_id() {
  return get_id_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
Proto_LTSMailReadItemRsp::get_id() const {
  return get_id_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
Proto_LTSMailReadItemRsp::mutable_get_id() {
  return &get_id_;
}

// repeated .proto_email.MailItem id = 5;
inline int Proto_LTSMailReadItemRsp::id_size() const {
  return id_.size();
}
inline void Proto_LTSMailReadItemRsp::clear_id() {
  id_.Clear();
}
inline const ::proto_email::MailItem& Proto_LTSMailReadItemRsp::id(int index) const {
  return id_.Get(index);
}
inline ::proto_email::MailItem* Proto_LTSMailReadItemRsp::mutable_id(int index) {
  return id_.Mutable(index);
}
inline ::proto_email::MailItem* Proto_LTSMailReadItemRsp::add_id() {
  return id_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
Proto_LTSMailReadItemRsp::id() const {
  return id_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
Proto_LTSMailReadItemRsp::mutable_id() {
  return &id_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto_ff::Proto_EmailSvrMsgID>() {
  return ::proto_ff::Proto_EmailSvrMsgID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fsvr_5femail_2eproto__INCLUDED
