// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_svr_bank.proto

#ifndef PROTOBUF_proto_5fsvr_5fbank_2eproto__INCLUDED
#define PROTOBUF_proto_5fsvr_5fbank_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "yd_fieldoptions.pb.h"
#include "proto_common.pb.h"
#include "proto_cs_bank.pb.h"
// @@protoc_insertion_point(includes)

namespace proto_ff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5fsvr_5fbank_2eproto();
void protobuf_AssignDesc_proto_5fsvr_5fbank_2eproto();
void protobuf_ShutdownFile_proto_5fsvr_5fbank_2eproto();

class Proto_STSGiveJettonAutoPush;

enum Proto_BankSvrMsgID {
  NF_GIVE_BANK_JETTON_AUTO_PSUH_TRANSFER = 270
};
bool Proto_BankSvrMsgID_IsValid(int value);
const Proto_BankSvrMsgID Proto_BankSvrMsgID_MIN = NF_GIVE_BANK_JETTON_AUTO_PSUH_TRANSFER;
const Proto_BankSvrMsgID Proto_BankSvrMsgID_MAX = NF_GIVE_BANK_JETTON_AUTO_PSUH_TRANSFER;
const int Proto_BankSvrMsgID_ARRAYSIZE = Proto_BankSvrMsgID_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto_BankSvrMsgID_descriptor();
inline const ::std::string& Proto_BankSvrMsgID_Name(Proto_BankSvrMsgID value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto_BankSvrMsgID_descriptor(), value);
}
inline bool Proto_BankSvrMsgID_Parse(
    const ::std::string& name, Proto_BankSvrMsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto_BankSvrMsgID>(
    Proto_BankSvrMsgID_descriptor(), name, value);
}
// ===================================================================

class Proto_STSGiveJettonAutoPush : public ::google::protobuf::Message {
 public:
  Proto_STSGiveJettonAutoPush();
  virtual ~Proto_STSGiveJettonAutoPush();

  Proto_STSGiveJettonAutoPush(const Proto_STSGiveJettonAutoPush& from);

  inline Proto_STSGiveJettonAutoPush& operator=(const Proto_STSGiveJettonAutoPush& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_STSGiveJettonAutoPush& default_instance();

  void Swap(Proto_STSGiveJettonAutoPush* other);

  // implements Message ----------------------------------------------

  Proto_STSGiveJettonAutoPush* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_STSGiveJettonAutoPush& from);
  void MergeFrom(const Proto_STSGiveJettonAutoPush& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // optional .proto_ff.tbGiveBankJetton record = 2;
  inline bool has_record() const;
  inline void clear_record();
  static const int kRecordFieldNumber = 2;
  inline const ::proto_ff::tbGiveBankJetton& record() const;
  inline ::proto_ff::tbGiveBankJetton* mutable_record();
  inline ::proto_ff::tbGiveBankJetton* release_record();
  inline void set_allocated_record(::proto_ff::tbGiveBankJetton* record);

  // @@protoc_insertion_point(class_scope:proto_ff.Proto_STSGiveJettonAutoPush)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_record();
  inline void clear_has_record();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::proto_ff::tbGiveBankJetton* record_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fsvr_5fbank_2eproto();
  friend void protobuf_AssignDesc_proto_5fsvr_5fbank_2eproto();
  friend void protobuf_ShutdownFile_proto_5fsvr_5fbank_2eproto();

  void InitAsDefaultInstance();
  static Proto_STSGiveJettonAutoPush* default_instance_;
};
// ===================================================================


// ===================================================================

// Proto_STSGiveJettonAutoPush

// optional uint64 user_id = 1;
inline bool Proto_STSGiveJettonAutoPush::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_STSGiveJettonAutoPush::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_STSGiveJettonAutoPush::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_STSGiveJettonAutoPush::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 Proto_STSGiveJettonAutoPush::user_id() const {
  return user_id_;
}
inline void Proto_STSGiveJettonAutoPush::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional .proto_ff.tbGiveBankJetton record = 2;
inline bool Proto_STSGiveJettonAutoPush::has_record() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_STSGiveJettonAutoPush::set_has_record() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_STSGiveJettonAutoPush::clear_has_record() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_STSGiveJettonAutoPush::clear_record() {
  if (record_ != NULL) record_->::proto_ff::tbGiveBankJetton::Clear();
  clear_has_record();
}
inline const ::proto_ff::tbGiveBankJetton& Proto_STSGiveJettonAutoPush::record() const {
  return record_ != NULL ? *record_ : *default_instance_->record_;
}
inline ::proto_ff::tbGiveBankJetton* Proto_STSGiveJettonAutoPush::mutable_record() {
  set_has_record();
  if (record_ == NULL) record_ = new ::proto_ff::tbGiveBankJetton;
  return record_;
}
inline ::proto_ff::tbGiveBankJetton* Proto_STSGiveJettonAutoPush::release_record() {
  clear_has_record();
  ::proto_ff::tbGiveBankJetton* temp = record_;
  record_ = NULL;
  return temp;
}
inline void Proto_STSGiveJettonAutoPush::set_allocated_record(::proto_ff::tbGiveBankJetton* record) {
  delete record_;
  record_ = record;
  if (record) {
    set_has_record();
  } else {
    clear_has_record();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto_ff::Proto_BankSvrMsgID>() {
  return ::proto_ff::Proto_BankSvrMsgID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fsvr_5fbank_2eproto__INCLUDED
