// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_svr_error.proto

#ifndef PROTOBUF_proto_5fsvr_5ferror_2eproto__INCLUDED
#define PROTOBUF_proto_5fsvr_5ferror_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace proto_ff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5fsvr_5ferror_2eproto();
void protobuf_AssignDesc_proto_5fsvr_5ferror_2eproto();
void protobuf_ShutdownFile_proto_5fsvr_5ferror_2eproto();


enum Proto_SVR_ErrorCode {
  ERR_CODE_SERVER_SYSTEM_ERROR = -1,
  ERR_CODE_SERVER_OK = 0
};
bool Proto_SVR_ErrorCode_IsValid(int value);
const Proto_SVR_ErrorCode Proto_SVR_ErrorCode_MIN = ERR_CODE_SERVER_SYSTEM_ERROR;
const Proto_SVR_ErrorCode Proto_SVR_ErrorCode_MAX = ERR_CODE_SERVER_OK;
const int Proto_SVR_ErrorCode_ARRAYSIZE = Proto_SVR_ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto_SVR_ErrorCode_descriptor();
inline const ::std::string& Proto_SVR_ErrorCode_Name(Proto_SVR_ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto_SVR_ErrorCode_descriptor(), value);
}
inline bool Proto_SVR_ErrorCode_Parse(
    const ::std::string& name, Proto_SVR_ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto_SVR_ErrorCode>(
    Proto_SVR_ErrorCode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto_ff::Proto_SVR_ErrorCode>() {
  return ::proto_ff::Proto_SVR_ErrorCode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fsvr_5ferror_2eproto__INCLUDED
