// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_cs_email.proto

#ifndef PROTOBUF_proto_5fcs_5femail_2eproto__INCLUDED
#define PROTOBUF_proto_5fcs_5femail_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto_email {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

class UserMailData;
class MailItem;
class Proto_CSMailListReq;
class Proto_CSMailListRsp;
class Proto_CSMailReadReq;
class Proto_CSMailReadRsp;
class Proto_CSMailGetItemReq;
class Proto_CSMailGetItemRsp;
class Proto_CSMailDelReq;
class Proto_CSMailDelRsp;
class Proto_CSMailAutoPushRsp;

enum Proto_EMAIL_CS_CMD {
  NF_CS_SNS_MAIL_LIST_REQ = 1150,
  NF_SC_SNS_MAIL_LIST_RSP = 1151,
  NF_CS_SNS_MAIL_READ_REQ = 1152,
  NF_SC_SNS_MAIL_READ_RSP = 1153,
  NF_CS_SNS_MAIL_DEL_REQ = 1154,
  NF_SC_SNS_MAIL_DEL_RSP = 1155,
  NF_SC_SNS_MAIL_AUTO_PUSH_RSP = 1156,
  NF_CS_SNS_MAIL_GET_ITEM_REQ = 1157,
  NF_SC_SNS_MAIL_GET_ITEM_RSP = 1158
};
bool Proto_EMAIL_CS_CMD_IsValid(int value);
const Proto_EMAIL_CS_CMD Proto_EMAIL_CS_CMD_MIN = NF_CS_SNS_MAIL_LIST_REQ;
const Proto_EMAIL_CS_CMD Proto_EMAIL_CS_CMD_MAX = NF_SC_SNS_MAIL_GET_ITEM_RSP;
const int Proto_EMAIL_CS_CMD_ARRAYSIZE = Proto_EMAIL_CS_CMD_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto_EMAIL_CS_CMD_descriptor();
inline const ::std::string& Proto_EMAIL_CS_CMD_Name(Proto_EMAIL_CS_CMD value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto_EMAIL_CS_CMD_descriptor(), value);
}
inline bool Proto_EMAIL_CS_CMD_Parse(
    const ::std::string& name, Proto_EMAIL_CS_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto_EMAIL_CS_CMD>(
    Proto_EMAIL_CS_CMD_descriptor(), name, value);
}
// ===================================================================

class UserMailData : public ::google::protobuf::Message {
 public:
  UserMailData();
  virtual ~UserMailData();

  UserMailData(const UserMailData& from);

  inline UserMailData& operator=(const UserMailData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserMailData& default_instance();

  void Swap(UserMailData* other);

  // implements Message ----------------------------------------------

  UserMailData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserMailData& from);
  void MergeFrom(const UserMailData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional string send_name = 2;
  inline bool has_send_name() const;
  inline void clear_send_name();
  static const int kSendNameFieldNumber = 2;
  inline const ::std::string& send_name() const;
  inline void set_send_name(const ::std::string& value);
  inline void set_send_name(const char* value);
  inline void set_send_name(const char* value, size_t size);
  inline ::std::string* mutable_send_name();
  inline ::std::string* release_send_name();
  inline void set_allocated_send_name(::std::string* send_name);

  // optional string title = 3;
  inline bool has_title() const;
  inline void clear_title();
  static const int kTitleFieldNumber = 3;
  inline const ::std::string& title() const;
  inline void set_title(const ::std::string& value);
  inline void set_title(const char* value);
  inline void set_title(const char* value, size_t size);
  inline ::std::string* mutable_title();
  inline ::std::string* release_title();
  inline void set_allocated_title(::std::string* title);

  // optional string content = 4;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 4;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // optional uint64 send_time = 5;
  inline bool has_send_time() const;
  inline void clear_send_time();
  static const int kSendTimeFieldNumber = 5;
  inline ::google::protobuf::uint64 send_time() const;
  inline void set_send_time(::google::protobuf::uint64 value);

  // optional uint32 status = 6;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 6;
  inline ::google::protobuf::uint32 status() const;
  inline void set_status(::google::protobuf::uint32 value);

  // optional int32 usAreaId = 7;
  inline bool has_usareaid() const;
  inline void clear_usareaid();
  static const int kUsAreaIdFieldNumber = 7;
  inline ::google::protobuf::int32 usareaid() const;
  inline void set_usareaid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_email.UserMailData)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_send_name();
  inline void clear_has_send_name();
  inline void set_has_title();
  inline void clear_has_title();
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_send_time();
  inline void clear_has_send_time();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_usareaid();
  inline void clear_has_usareaid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 id_;
  ::std::string* send_name_;
  ::std::string* title_;
  ::std::string* content_;
  ::google::protobuf::uint64 send_time_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::int32 usareaid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static UserMailData* default_instance_;
};
// -------------------------------------------------------------------

class MailItem : public ::google::protobuf::Message {
 public:
  MailItem();
  virtual ~MailItem();

  MailItem(const MailItem& from);

  inline MailItem& operator=(const MailItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MailItem& default_instance();

  void Swap(MailItem* other);

  // implements Message ----------------------------------------------

  MailItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailItem& from);
  void MergeFrom(const MailItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional int32 add_gold = 2;
  inline bool has_add_gold() const;
  inline void clear_add_gold();
  static const int kAddGoldFieldNumber = 2;
  inline ::google::protobuf::int32 add_gold() const;
  inline void set_add_gold(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_email.MailItem)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_add_gold();
  inline void clear_has_add_gold();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 id_;
  ::google::protobuf::int32 add_gold_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static MailItem* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailListReq : public ::google::protobuf::Message {
 public:
  Proto_CSMailListReq();
  virtual ~Proto_CSMailListReq();

  Proto_CSMailListReq(const Proto_CSMailListReq& from);

  inline Proto_CSMailListReq& operator=(const Proto_CSMailListReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailListReq& default_instance();

  void Swap(Proto_CSMailListReq* other);

  // implements Message ----------------------------------------------

  Proto_CSMailListReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailListReq& from);
  void MergeFrom(const Proto_CSMailListReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 begin = 1;
  inline bool has_begin() const;
  inline void clear_begin();
  static const int kBeginFieldNumber = 1;
  inline ::google::protobuf::int32 begin() const;
  inline void set_begin(::google::protobuf::int32 value);

  // optional int32 end = 2;
  inline bool has_end() const;
  inline void clear_end();
  static const int kEndFieldNumber = 2;
  inline ::google::protobuf::int32 end() const;
  inline void set_end(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailListReq)
 private:
  inline void set_has_begin();
  inline void clear_has_begin();
  inline void set_has_end();
  inline void clear_has_end();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 begin_;
  ::google::protobuf::int32 end_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailListReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailListRsp : public ::google::protobuf::Message {
 public:
  Proto_CSMailListRsp();
  virtual ~Proto_CSMailListRsp();

  Proto_CSMailListRsp(const Proto_CSMailListRsp& from);

  inline Proto_CSMailListRsp& operator=(const Proto_CSMailListRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailListRsp& default_instance();

  void Swap(Proto_CSMailListRsp* other);

  // implements Message ----------------------------------------------

  Proto_CSMailListRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailListRsp& from);
  void MergeFrom(const Proto_CSMailListRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // repeated .proto_email.UserMailData role_mail_list = 2;
  inline int role_mail_list_size() const;
  inline void clear_role_mail_list();
  static const int kRoleMailListFieldNumber = 2;
  inline const ::proto_email::UserMailData& role_mail_list(int index) const;
  inline ::proto_email::UserMailData* mutable_role_mail_list(int index);
  inline ::proto_email::UserMailData* add_role_mail_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >&
      role_mail_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >*
      mutable_role_mail_list();

  // optional int32 all_count = 3;
  inline bool has_all_count() const;
  inline void clear_all_count();
  static const int kAllCountFieldNumber = 3;
  inline ::google::protobuf::int32 all_count() const;
  inline void set_all_count(::google::protobuf::int32 value);

  // optional int32 no_read_count = 4;
  inline bool has_no_read_count() const;
  inline void clear_no_read_count();
  static const int kNoReadCountFieldNumber = 4;
  inline ::google::protobuf::int32 no_read_count() const;
  inline void set_no_read_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailListRsp)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_all_count();
  inline void clear_has_all_count();
  inline void set_has_no_read_count();
  inline void clear_has_no_read_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData > role_mail_list_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 all_count_;
  ::google::protobuf::int32 no_read_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailListRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailReadReq : public ::google::protobuf::Message {
 public:
  Proto_CSMailReadReq();
  virtual ~Proto_CSMailReadReq();

  Proto_CSMailReadReq(const Proto_CSMailReadReq& from);

  inline Proto_CSMailReadReq& operator=(const Proto_CSMailReadReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailReadReq& default_instance();

  void Swap(Proto_CSMailReadReq* other);

  // implements Message ----------------------------------------------

  Proto_CSMailReadReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailReadReq& from);
  void MergeFrom(const Proto_CSMailReadReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 mail_id = 1;
  inline bool has_mail_id() const;
  inline void clear_mail_id();
  static const int kMailIdFieldNumber = 1;
  inline ::google::protobuf::uint64 mail_id() const;
  inline void set_mail_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailReadReq)
 private:
  inline void set_has_mail_id();
  inline void clear_has_mail_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 mail_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailReadReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailReadRsp : public ::google::protobuf::Message {
 public:
  Proto_CSMailReadRsp();
  virtual ~Proto_CSMailReadRsp();

  Proto_CSMailReadRsp(const Proto_CSMailReadRsp& from);

  inline Proto_CSMailReadRsp& operator=(const Proto_CSMailReadRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailReadRsp& default_instance();

  void Swap(Proto_CSMailReadRsp* other);

  // implements Message ----------------------------------------------

  Proto_CSMailReadRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailReadRsp& from);
  void MergeFrom(const Proto_CSMailReadRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // repeated uint64 mail_id_list = 2;
  inline int mail_id_list_size() const;
  inline void clear_mail_id_list();
  static const int kMailIdListFieldNumber = 2;
  inline ::google::protobuf::uint64 mail_id_list(int index) const;
  inline void set_mail_id_list(int index, ::google::protobuf::uint64 value);
  inline void add_mail_id_list(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      mail_id_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_mail_id_list();

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailReadRsp)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > mail_id_list_;
  ::google::protobuf::uint32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailReadRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailGetItemReq : public ::google::protobuf::Message {
 public:
  Proto_CSMailGetItemReq();
  virtual ~Proto_CSMailGetItemReq();

  Proto_CSMailGetItemReq(const Proto_CSMailGetItemReq& from);

  inline Proto_CSMailGetItemReq& operator=(const Proto_CSMailGetItemReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailGetItemReq& default_instance();

  void Swap(Proto_CSMailGetItemReq* other);

  // implements Message ----------------------------------------------

  Proto_CSMailGetItemReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailGetItemReq& from);
  void MergeFrom(const Proto_CSMailGetItemReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 mail_id = 1;
  inline bool has_mail_id() const;
  inline void clear_mail_id();
  static const int kMailIdFieldNumber = 1;
  inline ::google::protobuf::uint64 mail_id() const;
  inline void set_mail_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailGetItemReq)
 private:
  inline void set_has_mail_id();
  inline void clear_has_mail_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 mail_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailGetItemReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailGetItemRsp : public ::google::protobuf::Message {
 public:
  Proto_CSMailGetItemRsp();
  virtual ~Proto_CSMailGetItemRsp();

  Proto_CSMailGetItemRsp(const Proto_CSMailGetItemRsp& from);

  inline Proto_CSMailGetItemRsp& operator=(const Proto_CSMailGetItemRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailGetItemRsp& default_instance();

  void Swap(Proto_CSMailGetItemRsp* other);

  // implements Message ----------------------------------------------

  Proto_CSMailGetItemRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailGetItemRsp& from);
  void MergeFrom(const Proto_CSMailGetItemRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_email.MailItem item_list = 1;
  inline int item_list_size() const;
  inline void clear_item_list();
  static const int kItemListFieldNumber = 1;
  inline const ::proto_email::MailItem& item_list(int index) const;
  inline ::proto_email::MailItem* mutable_item_list(int index);
  inline ::proto_email::MailItem* add_item_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
      item_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
      mutable_item_list();

  // optional uint32 no_read_count = 2;
  inline bool has_no_read_count() const;
  inline void clear_no_read_count();
  static const int kNoReadCountFieldNumber = 2;
  inline ::google::protobuf::uint32 no_read_count() const;
  inline void set_no_read_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailGetItemRsp)
 private:
  inline void set_has_no_read_count();
  inline void clear_has_no_read_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem > item_list_;
  ::google::protobuf::uint32 no_read_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailGetItemRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailDelReq : public ::google::protobuf::Message {
 public:
  Proto_CSMailDelReq();
  virtual ~Proto_CSMailDelReq();

  Proto_CSMailDelReq(const Proto_CSMailDelReq& from);

  inline Proto_CSMailDelReq& operator=(const Proto_CSMailDelReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailDelReq& default_instance();

  void Swap(Proto_CSMailDelReq* other);

  // implements Message ----------------------------------------------

  Proto_CSMailDelReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailDelReq& from);
  void MergeFrom(const Proto_CSMailDelReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 mail_id = 1;
  inline int mail_id_size() const;
  inline void clear_mail_id();
  static const int kMailIdFieldNumber = 1;
  inline ::google::protobuf::uint64 mail_id(int index) const;
  inline void set_mail_id(int index, ::google::protobuf::uint64 value);
  inline void add_mail_id(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      mail_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_mail_id();

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailDelReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > mail_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailDelReq* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailDelRsp : public ::google::protobuf::Message {
 public:
  Proto_CSMailDelRsp();
  virtual ~Proto_CSMailDelRsp();

  Proto_CSMailDelRsp(const Proto_CSMailDelRsp& from);

  inline Proto_CSMailDelRsp& operator=(const Proto_CSMailDelRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailDelRsp& default_instance();

  void Swap(Proto_CSMailDelRsp* other);

  // implements Message ----------------------------------------------

  Proto_CSMailDelRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailDelRsp& from);
  void MergeFrom(const Proto_CSMailDelRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // repeated uint64 mail_id_list = 2;
  inline int mail_id_list_size() const;
  inline void clear_mail_id_list();
  static const int kMailIdListFieldNumber = 2;
  inline ::google::protobuf::uint64 mail_id_list(int index) const;
  inline void set_mail_id_list(int index, ::google::protobuf::uint64 value);
  inline void add_mail_id_list(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      mail_id_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_mail_id_list();

  // optional int32 all_count = 3;
  inline bool has_all_count() const;
  inline void clear_all_count();
  static const int kAllCountFieldNumber = 3;
  inline ::google::protobuf::int32 all_count() const;
  inline void set_all_count(::google::protobuf::int32 value);

  // optional int32 no_read_count = 4;
  inline bool has_no_read_count() const;
  inline void clear_no_read_count();
  static const int kNoReadCountFieldNumber = 4;
  inline ::google::protobuf::int32 no_read_count() const;
  inline void set_no_read_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailDelRsp)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_all_count();
  inline void clear_has_all_count();
  inline void set_has_no_read_count();
  inline void clear_has_no_read_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > mail_id_list_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 all_count_;
  ::google::protobuf::int32 no_read_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailDelRsp* default_instance_;
};
// -------------------------------------------------------------------

class Proto_CSMailAutoPushRsp : public ::google::protobuf::Message {
 public:
  Proto_CSMailAutoPushRsp();
  virtual ~Proto_CSMailAutoPushRsp();

  Proto_CSMailAutoPushRsp(const Proto_CSMailAutoPushRsp& from);

  inline Proto_CSMailAutoPushRsp& operator=(const Proto_CSMailAutoPushRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto_CSMailAutoPushRsp& default_instance();

  void Swap(Proto_CSMailAutoPushRsp* other);

  // implements Message ----------------------------------------------

  Proto_CSMailAutoPushRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto_CSMailAutoPushRsp& from);
  void MergeFrom(const Proto_CSMailAutoPushRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 all_count = 1;
  inline bool has_all_count() const;
  inline void clear_all_count();
  static const int kAllCountFieldNumber = 1;
  inline ::google::protobuf::int32 all_count() const;
  inline void set_all_count(::google::protobuf::int32 value);

  // optional int32 no_read_count = 2;
  inline bool has_no_read_count() const;
  inline void clear_no_read_count();
  static const int kNoReadCountFieldNumber = 2;
  inline ::google::protobuf::int32 no_read_count() const;
  inline void set_no_read_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_email.Proto_CSMailAutoPushRsp)
 private:
  inline void set_has_all_count();
  inline void clear_has_all_count();
  inline void set_has_no_read_count();
  inline void clear_has_no_read_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 all_count_;
  ::google::protobuf::int32 no_read_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_AssignDesc_proto_5fcs_5femail_2eproto();
  friend void protobuf_ShutdownFile_proto_5fcs_5femail_2eproto();

  void InitAsDefaultInstance();
  static Proto_CSMailAutoPushRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// UserMailData

// optional uint64 id = 1;
inline bool UserMailData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserMailData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserMailData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserMailData::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 UserMailData::id() const {
  return id_;
}
inline void UserMailData::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}

// optional string send_name = 2;
inline bool UserMailData::has_send_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserMailData::set_has_send_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserMailData::clear_has_send_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserMailData::clear_send_name() {
  if (send_name_ != &::google::protobuf::internal::kEmptyString) {
    send_name_->clear();
  }
  clear_has_send_name();
}
inline const ::std::string& UserMailData::send_name() const {
  return *send_name_;
}
inline void UserMailData::set_send_name(const ::std::string& value) {
  set_has_send_name();
  if (send_name_ == &::google::protobuf::internal::kEmptyString) {
    send_name_ = new ::std::string;
  }
  send_name_->assign(value);
}
inline void UserMailData::set_send_name(const char* value) {
  set_has_send_name();
  if (send_name_ == &::google::protobuf::internal::kEmptyString) {
    send_name_ = new ::std::string;
  }
  send_name_->assign(value);
}
inline void UserMailData::set_send_name(const char* value, size_t size) {
  set_has_send_name();
  if (send_name_ == &::google::protobuf::internal::kEmptyString) {
    send_name_ = new ::std::string;
  }
  send_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserMailData::mutable_send_name() {
  set_has_send_name();
  if (send_name_ == &::google::protobuf::internal::kEmptyString) {
    send_name_ = new ::std::string;
  }
  return send_name_;
}
inline ::std::string* UserMailData::release_send_name() {
  clear_has_send_name();
  if (send_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = send_name_;
    send_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserMailData::set_allocated_send_name(::std::string* send_name) {
  if (send_name_ != &::google::protobuf::internal::kEmptyString) {
    delete send_name_;
  }
  if (send_name) {
    set_has_send_name();
    send_name_ = send_name;
  } else {
    clear_has_send_name();
    send_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string title = 3;
inline bool UserMailData::has_title() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserMailData::set_has_title() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserMailData::clear_has_title() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserMailData::clear_title() {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    title_->clear();
  }
  clear_has_title();
}
inline const ::std::string& UserMailData::title() const {
  return *title_;
}
inline void UserMailData::set_title(const ::std::string& value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void UserMailData::set_title(const char* value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void UserMailData::set_title(const char* value, size_t size) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserMailData::mutable_title() {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  return title_;
}
inline ::std::string* UserMailData::release_title() {
  clear_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = title_;
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserMailData::set_allocated_title(::std::string* title) {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    delete title_;
  }
  if (title) {
    set_has_title();
    title_ = title;
  } else {
    clear_has_title();
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string content = 4;
inline bool UserMailData::has_content() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UserMailData::set_has_content() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UserMailData::clear_has_content() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UserMailData::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& UserMailData::content() const {
  return *content_;
}
inline void UserMailData::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void UserMailData::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void UserMailData::set_content(const char* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserMailData::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* UserMailData::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserMailData::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional uint64 send_time = 5;
inline bool UserMailData::has_send_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void UserMailData::set_has_send_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void UserMailData::clear_has_send_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void UserMailData::clear_send_time() {
  send_time_ = GOOGLE_ULONGLONG(0);
  clear_has_send_time();
}
inline ::google::protobuf::uint64 UserMailData::send_time() const {
  return send_time_;
}
inline void UserMailData::set_send_time(::google::protobuf::uint64 value) {
  set_has_send_time();
  send_time_ = value;
}

// optional uint32 status = 6;
inline bool UserMailData::has_status() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void UserMailData::set_has_status() {
  _has_bits_[0] |= 0x00000020u;
}
inline void UserMailData::clear_has_status() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void UserMailData::clear_status() {
  status_ = 0u;
  clear_has_status();
}
inline ::google::protobuf::uint32 UserMailData::status() const {
  return status_;
}
inline void UserMailData::set_status(::google::protobuf::uint32 value) {
  set_has_status();
  status_ = value;
}

// optional int32 usAreaId = 7;
inline bool UserMailData::has_usareaid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void UserMailData::set_has_usareaid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void UserMailData::clear_has_usareaid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void UserMailData::clear_usareaid() {
  usareaid_ = 0;
  clear_has_usareaid();
}
inline ::google::protobuf::int32 UserMailData::usareaid() const {
  return usareaid_;
}
inline void UserMailData::set_usareaid(::google::protobuf::int32 value) {
  set_has_usareaid();
  usareaid_ = value;
}

// -------------------------------------------------------------------

// MailItem

// optional uint64 id = 1;
inline bool MailItem::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailItem::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailItem::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailItem::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 MailItem::id() const {
  return id_;
}
inline void MailItem::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}

// optional int32 add_gold = 2;
inline bool MailItem::has_add_gold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MailItem::set_has_add_gold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MailItem::clear_has_add_gold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MailItem::clear_add_gold() {
  add_gold_ = 0;
  clear_has_add_gold();
}
inline ::google::protobuf::int32 MailItem::add_gold() const {
  return add_gold_;
}
inline void MailItem::set_add_gold(::google::protobuf::int32 value) {
  set_has_add_gold();
  add_gold_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailListReq

// optional int32 begin = 1;
inline bool Proto_CSMailListReq::has_begin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailListReq::set_has_begin() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailListReq::clear_has_begin() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailListReq::clear_begin() {
  begin_ = 0;
  clear_has_begin();
}
inline ::google::protobuf::int32 Proto_CSMailListReq::begin() const {
  return begin_;
}
inline void Proto_CSMailListReq::set_begin(::google::protobuf::int32 value) {
  set_has_begin();
  begin_ = value;
}

// optional int32 end = 2;
inline bool Proto_CSMailListReq::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_CSMailListReq::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_CSMailListReq::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_CSMailListReq::clear_end() {
  end_ = 0;
  clear_has_end();
}
inline ::google::protobuf::int32 Proto_CSMailListReq::end() const {
  return end_;
}
inline void Proto_CSMailListReq::set_end(::google::protobuf::int32 value) {
  set_has_end();
  end_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailListRsp

// optional int32 result = 1;
inline bool Proto_CSMailListRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailListRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailListRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailListRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 Proto_CSMailListRsp::result() const {
  return result_;
}
inline void Proto_CSMailListRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// repeated .proto_email.UserMailData role_mail_list = 2;
inline int Proto_CSMailListRsp::role_mail_list_size() const {
  return role_mail_list_.size();
}
inline void Proto_CSMailListRsp::clear_role_mail_list() {
  role_mail_list_.Clear();
}
inline const ::proto_email::UserMailData& Proto_CSMailListRsp::role_mail_list(int index) const {
  return role_mail_list_.Get(index);
}
inline ::proto_email::UserMailData* Proto_CSMailListRsp::mutable_role_mail_list(int index) {
  return role_mail_list_.Mutable(index);
}
inline ::proto_email::UserMailData* Proto_CSMailListRsp::add_role_mail_list() {
  return role_mail_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >&
Proto_CSMailListRsp::role_mail_list() const {
  return role_mail_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_email::UserMailData >*
Proto_CSMailListRsp::mutable_role_mail_list() {
  return &role_mail_list_;
}

// optional int32 all_count = 3;
inline bool Proto_CSMailListRsp::has_all_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto_CSMailListRsp::set_has_all_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto_CSMailListRsp::clear_has_all_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto_CSMailListRsp::clear_all_count() {
  all_count_ = 0;
  clear_has_all_count();
}
inline ::google::protobuf::int32 Proto_CSMailListRsp::all_count() const {
  return all_count_;
}
inline void Proto_CSMailListRsp::set_all_count(::google::protobuf::int32 value) {
  set_has_all_count();
  all_count_ = value;
}

// optional int32 no_read_count = 4;
inline bool Proto_CSMailListRsp::has_no_read_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto_CSMailListRsp::set_has_no_read_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto_CSMailListRsp::clear_has_no_read_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto_CSMailListRsp::clear_no_read_count() {
  no_read_count_ = 0;
  clear_has_no_read_count();
}
inline ::google::protobuf::int32 Proto_CSMailListRsp::no_read_count() const {
  return no_read_count_;
}
inline void Proto_CSMailListRsp::set_no_read_count(::google::protobuf::int32 value) {
  set_has_no_read_count();
  no_read_count_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailReadReq

// optional uint64 mail_id = 1;
inline bool Proto_CSMailReadReq::has_mail_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailReadReq::set_has_mail_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailReadReq::clear_has_mail_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailReadReq::clear_mail_id() {
  mail_id_ = GOOGLE_ULONGLONG(0);
  clear_has_mail_id();
}
inline ::google::protobuf::uint64 Proto_CSMailReadReq::mail_id() const {
  return mail_id_;
}
inline void Proto_CSMailReadReq::set_mail_id(::google::protobuf::uint64 value) {
  set_has_mail_id();
  mail_id_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailReadRsp

// optional uint32 result = 1;
inline bool Proto_CSMailReadRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailReadRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailReadRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailReadRsp::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 Proto_CSMailReadRsp::result() const {
  return result_;
}
inline void Proto_CSMailReadRsp::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
}

// repeated uint64 mail_id_list = 2;
inline int Proto_CSMailReadRsp::mail_id_list_size() const {
  return mail_id_list_.size();
}
inline void Proto_CSMailReadRsp::clear_mail_id_list() {
  mail_id_list_.Clear();
}
inline ::google::protobuf::uint64 Proto_CSMailReadRsp::mail_id_list(int index) const {
  return mail_id_list_.Get(index);
}
inline void Proto_CSMailReadRsp::set_mail_id_list(int index, ::google::protobuf::uint64 value) {
  mail_id_list_.Set(index, value);
}
inline void Proto_CSMailReadRsp::add_mail_id_list(::google::protobuf::uint64 value) {
  mail_id_list_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Proto_CSMailReadRsp::mail_id_list() const {
  return mail_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Proto_CSMailReadRsp::mutable_mail_id_list() {
  return &mail_id_list_;
}

// -------------------------------------------------------------------

// Proto_CSMailGetItemReq

// optional uint64 mail_id = 1;
inline bool Proto_CSMailGetItemReq::has_mail_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailGetItemReq::set_has_mail_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailGetItemReq::clear_has_mail_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailGetItemReq::clear_mail_id() {
  mail_id_ = GOOGLE_ULONGLONG(0);
  clear_has_mail_id();
}
inline ::google::protobuf::uint64 Proto_CSMailGetItemReq::mail_id() const {
  return mail_id_;
}
inline void Proto_CSMailGetItemReq::set_mail_id(::google::protobuf::uint64 value) {
  set_has_mail_id();
  mail_id_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailGetItemRsp

// repeated .proto_email.MailItem item_list = 1;
inline int Proto_CSMailGetItemRsp::item_list_size() const {
  return item_list_.size();
}
inline void Proto_CSMailGetItemRsp::clear_item_list() {
  item_list_.Clear();
}
inline const ::proto_email::MailItem& Proto_CSMailGetItemRsp::item_list(int index) const {
  return item_list_.Get(index);
}
inline ::proto_email::MailItem* Proto_CSMailGetItemRsp::mutable_item_list(int index) {
  return item_list_.Mutable(index);
}
inline ::proto_email::MailItem* Proto_CSMailGetItemRsp::add_item_list() {
  return item_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >&
Proto_CSMailGetItemRsp::item_list() const {
  return item_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_email::MailItem >*
Proto_CSMailGetItemRsp::mutable_item_list() {
  return &item_list_;
}

// optional uint32 no_read_count = 2;
inline bool Proto_CSMailGetItemRsp::has_no_read_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_CSMailGetItemRsp::set_has_no_read_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_CSMailGetItemRsp::clear_has_no_read_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_CSMailGetItemRsp::clear_no_read_count() {
  no_read_count_ = 0u;
  clear_has_no_read_count();
}
inline ::google::protobuf::uint32 Proto_CSMailGetItemRsp::no_read_count() const {
  return no_read_count_;
}
inline void Proto_CSMailGetItemRsp::set_no_read_count(::google::protobuf::uint32 value) {
  set_has_no_read_count();
  no_read_count_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailDelReq

// repeated uint64 mail_id = 1;
inline int Proto_CSMailDelReq::mail_id_size() const {
  return mail_id_.size();
}
inline void Proto_CSMailDelReq::clear_mail_id() {
  mail_id_.Clear();
}
inline ::google::protobuf::uint64 Proto_CSMailDelReq::mail_id(int index) const {
  return mail_id_.Get(index);
}
inline void Proto_CSMailDelReq::set_mail_id(int index, ::google::protobuf::uint64 value) {
  mail_id_.Set(index, value);
}
inline void Proto_CSMailDelReq::add_mail_id(::google::protobuf::uint64 value) {
  mail_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Proto_CSMailDelReq::mail_id() const {
  return mail_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Proto_CSMailDelReq::mutable_mail_id() {
  return &mail_id_;
}

// -------------------------------------------------------------------

// Proto_CSMailDelRsp

// optional int32 result = 1;
inline bool Proto_CSMailDelRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailDelRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailDelRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailDelRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 Proto_CSMailDelRsp::result() const {
  return result_;
}
inline void Proto_CSMailDelRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// repeated uint64 mail_id_list = 2;
inline int Proto_CSMailDelRsp::mail_id_list_size() const {
  return mail_id_list_.size();
}
inline void Proto_CSMailDelRsp::clear_mail_id_list() {
  mail_id_list_.Clear();
}
inline ::google::protobuf::uint64 Proto_CSMailDelRsp::mail_id_list(int index) const {
  return mail_id_list_.Get(index);
}
inline void Proto_CSMailDelRsp::set_mail_id_list(int index, ::google::protobuf::uint64 value) {
  mail_id_list_.Set(index, value);
}
inline void Proto_CSMailDelRsp::add_mail_id_list(::google::protobuf::uint64 value) {
  mail_id_list_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Proto_CSMailDelRsp::mail_id_list() const {
  return mail_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Proto_CSMailDelRsp::mutable_mail_id_list() {
  return &mail_id_list_;
}

// optional int32 all_count = 3;
inline bool Proto_CSMailDelRsp::has_all_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto_CSMailDelRsp::set_has_all_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto_CSMailDelRsp::clear_has_all_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto_CSMailDelRsp::clear_all_count() {
  all_count_ = 0;
  clear_has_all_count();
}
inline ::google::protobuf::int32 Proto_CSMailDelRsp::all_count() const {
  return all_count_;
}
inline void Proto_CSMailDelRsp::set_all_count(::google::protobuf::int32 value) {
  set_has_all_count();
  all_count_ = value;
}

// optional int32 no_read_count = 4;
inline bool Proto_CSMailDelRsp::has_no_read_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto_CSMailDelRsp::set_has_no_read_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto_CSMailDelRsp::clear_has_no_read_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto_CSMailDelRsp::clear_no_read_count() {
  no_read_count_ = 0;
  clear_has_no_read_count();
}
inline ::google::protobuf::int32 Proto_CSMailDelRsp::no_read_count() const {
  return no_read_count_;
}
inline void Proto_CSMailDelRsp::set_no_read_count(::google::protobuf::int32 value) {
  set_has_no_read_count();
  no_read_count_ = value;
}

// -------------------------------------------------------------------

// Proto_CSMailAutoPushRsp

// optional int32 all_count = 1;
inline bool Proto_CSMailAutoPushRsp::has_all_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto_CSMailAutoPushRsp::set_has_all_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto_CSMailAutoPushRsp::clear_has_all_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto_CSMailAutoPushRsp::clear_all_count() {
  all_count_ = 0;
  clear_has_all_count();
}
inline ::google::protobuf::int32 Proto_CSMailAutoPushRsp::all_count() const {
  return all_count_;
}
inline void Proto_CSMailAutoPushRsp::set_all_count(::google::protobuf::int32 value) {
  set_has_all_count();
  all_count_ = value;
}

// optional int32 no_read_count = 2;
inline bool Proto_CSMailAutoPushRsp::has_no_read_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto_CSMailAutoPushRsp::set_has_no_read_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto_CSMailAutoPushRsp::clear_has_no_read_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto_CSMailAutoPushRsp::clear_no_read_count() {
  no_read_count_ = 0;
  clear_has_no_read_count();
}
inline ::google::protobuf::int32 Proto_CSMailAutoPushRsp::no_read_count() const {
  return no_read_count_;
}
inline void Proto_CSMailAutoPushRsp::set_no_read_count(::google::protobuf::int32 value) {
  set_has_no_read_count();
  no_read_count_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_email

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto_email::Proto_EMAIL_CS_CMD>() {
  return ::proto_email::Proto_EMAIL_CS_CMD_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fcs_5femail_2eproto__INCLUDED
