// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_svr_bank.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto_svr_bank.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto_ff {

namespace {

const ::google::protobuf::Descriptor* Proto_STSGiveJettonAutoPush_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Proto_STSGiveJettonAutoPush_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Proto_BankSvrMsgID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_5fsvr_5fbank_2eproto() {
  protobuf_AddDesc_proto_5fsvr_5fbank_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto_svr_bank.proto");
  GOOGLE_CHECK(file != NULL);
  Proto_STSGiveJettonAutoPush_descriptor_ = file->message_type(0);
  static const int Proto_STSGiveJettonAutoPush_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Proto_STSGiveJettonAutoPush, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Proto_STSGiveJettonAutoPush, record_),
  };
  Proto_STSGiveJettonAutoPush_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Proto_STSGiveJettonAutoPush_descriptor_,
      Proto_STSGiveJettonAutoPush::default_instance_,
      Proto_STSGiveJettonAutoPush_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Proto_STSGiveJettonAutoPush, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Proto_STSGiveJettonAutoPush, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Proto_STSGiveJettonAutoPush));
  Proto_BankSvrMsgID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_5fsvr_5fbank_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Proto_STSGiveJettonAutoPush_descriptor_, &Proto_STSGiveJettonAutoPush::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_5fsvr_5fbank_2eproto() {
  delete Proto_STSGiveJettonAutoPush::default_instance_;
  delete Proto_STSGiveJettonAutoPush_reflection_;
}

void protobuf_AddDesc_proto_5fsvr_5fbank_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::yd_fieldoptions::protobuf_AddDesc_yd_5ffieldoptions_2eproto();
  ::proto_ff::protobuf_AddDesc_proto_5fcommon_2eproto();
  ::proto_bank::protobuf_AddDesc_proto_5fcs_5fbank_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024proto_svr_bank.proto\022\010proto_ff\032\025yd_fie"
    "ldoptions.proto\032\022proto_common.proto\032\023pro"
    "to_cs_bank.proto\"Z\n\033Proto_STSGiveJettonA"
    "utoPush\022\017\n\007user_id\030\001 \001(\004\022*\n\006record\030\002 \001(\013"
    "2\032.proto_ff.tbGiveBankJetton*A\n\022Proto_Ba"
    "nkSvrMsgID\022+\n&NF_GIVE_BANK_JETTON_AUTO_P"
    "SUH_TRANSFER\020\216\002", 255);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_svr_bank.proto", &protobuf_RegisterTypes);
  Proto_STSGiveJettonAutoPush::default_instance_ = new Proto_STSGiveJettonAutoPush();
  Proto_STSGiveJettonAutoPush::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_5fsvr_5fbank_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_5fsvr_5fbank_2eproto {
  StaticDescriptorInitializer_proto_5fsvr_5fbank_2eproto() {
    protobuf_AddDesc_proto_5fsvr_5fbank_2eproto();
  }
} static_descriptor_initializer_proto_5fsvr_5fbank_2eproto_;
const ::google::protobuf::EnumDescriptor* Proto_BankSvrMsgID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Proto_BankSvrMsgID_descriptor_;
}
bool Proto_BankSvrMsgID_IsValid(int value) {
  switch(value) {
    case 270:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int Proto_STSGiveJettonAutoPush::kUserIdFieldNumber;
const int Proto_STSGiveJettonAutoPush::kRecordFieldNumber;
#endif  // !_MSC_VER

Proto_STSGiveJettonAutoPush::Proto_STSGiveJettonAutoPush()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Proto_STSGiveJettonAutoPush::InitAsDefaultInstance() {
  record_ = const_cast< ::proto_ff::tbGiveBankJetton*>(&::proto_ff::tbGiveBankJetton::default_instance());
}

Proto_STSGiveJettonAutoPush::Proto_STSGiveJettonAutoPush(const Proto_STSGiveJettonAutoPush& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Proto_STSGiveJettonAutoPush::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = GOOGLE_ULONGLONG(0);
  record_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Proto_STSGiveJettonAutoPush::~Proto_STSGiveJettonAutoPush() {
  SharedDtor();
}

void Proto_STSGiveJettonAutoPush::SharedDtor() {
  if (this != default_instance_) {
    delete record_;
  }
}

void Proto_STSGiveJettonAutoPush::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Proto_STSGiveJettonAutoPush::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Proto_STSGiveJettonAutoPush_descriptor_;
}

const Proto_STSGiveJettonAutoPush& Proto_STSGiveJettonAutoPush::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fsvr_5fbank_2eproto();
  return *default_instance_;
}

Proto_STSGiveJettonAutoPush* Proto_STSGiveJettonAutoPush::default_instance_ = NULL;

Proto_STSGiveJettonAutoPush* Proto_STSGiveJettonAutoPush::New() const {
  return new Proto_STSGiveJettonAutoPush;
}

void Proto_STSGiveJettonAutoPush::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = GOOGLE_ULONGLONG(0);
    if (has_record()) {
      if (record_ != NULL) record_->::proto_ff::tbGiveBankJetton::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Proto_STSGiveJettonAutoPush::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_record;
        break;
      }

      // optional .proto_ff.tbGiveBankJetton record = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_record:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_record()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Proto_STSGiveJettonAutoPush::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint64 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->user_id(), output);
  }

  // optional .proto_ff.tbGiveBankJetton record = 2;
  if (has_record()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->record(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Proto_STSGiveJettonAutoPush::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint64 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->user_id(), target);
  }

  // optional .proto_ff.tbGiveBankJetton record = 2;
  if (has_record()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->record(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Proto_STSGiveJettonAutoPush::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint64 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->user_id());
    }

    // optional .proto_ff.tbGiveBankJetton record = 2;
    if (has_record()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->record());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Proto_STSGiveJettonAutoPush::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Proto_STSGiveJettonAutoPush* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Proto_STSGiveJettonAutoPush*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Proto_STSGiveJettonAutoPush::MergeFrom(const Proto_STSGiveJettonAutoPush& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_record()) {
      mutable_record()->::proto_ff::tbGiveBankJetton::MergeFrom(from.record());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Proto_STSGiveJettonAutoPush::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Proto_STSGiveJettonAutoPush::CopyFrom(const Proto_STSGiveJettonAutoPush& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Proto_STSGiveJettonAutoPush::IsInitialized() const {

  if (has_record()) {
    if (!this->record().IsInitialized()) return false;
  }
  return true;
}

void Proto_STSGiveJettonAutoPush::Swap(Proto_STSGiveJettonAutoPush* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(record_, other->record_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Proto_STSGiveJettonAutoPush::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Proto_STSGiveJettonAutoPush_descriptor_;
  metadata.reflection = Proto_STSGiveJettonAutoPush_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

// @@protoc_insertion_point(global_scope)
