// -------------------------------------------------------------------------
//    @FileName         :    NFSubGameTypeDefines.h
//    @Author           :    xxxxx
//    @Date             :   xxxx-xx-xx
//    @Email			:    xxxxxxxxx@xxx.xxx
//    @Module           :    NFPluginModule
//
// -------------------------------------------------------------------------

#pragma once
#include "NFTypeDefines.h"

typedef enum
{
	EOT_SG_BEGIN_ID = EOT_SUB_GAME_BEGIN_ID, //

	EOT_FISH_ROOM_CONFIG_DESC_ID = 301,
	EOT_FISH_LEVEL_CONFIG_DESC_ID = 302,
	EOT_GM_CTRL_LEVEL_DESC_ID = 303,
	EOT_GAME_FISH_DESK_HANDLE_ID = 304,
	EOT_GAME_FISH_ROBOT_HANDLE_ID = 305,
	EOT_DESK_INFO_DESC_ID = 306,
	EOT_FISH_ALGO_DESC_ID = 307,
	EOT_FISH_CONFIG_DESC_ID = 308,
	EOT_FISH_ROOM_CONFIG_MGR_ID = 309,
	EOT_FISH_ALGO_MGR_ID = 310,
	EOT_FISH_ALGO_RMB_MGR_ID = 311,
	EOT_FISH_PLAYER_TYPE_ALGO_ID = 312,
	EOT_FISH_PLAYER_TYPE_ALGO_RMB_ID = 313,
	EOT_FISH_PLAYER_TYPE_ALGO_RANDRATE_ID = 314,
	EOT_GUN_CONFIG_ID = 315,
	EOT_FISH_ROOM_MGR_ID = 316,
	EOT_FISH_GROUP_MGR_ID = 317,
	EOT_FISH_TRACE_MGR_ID = 318,
	EOT_GAME_LEVEL_CONFIG_DESC_ID = 319,
	EOT_GAME_FISH_SETTING_DESC_ID = 320,
	EOT_GAME_FISH_PROMPT_CFG_DESC_ID = 321,
    EOT_GAME_FISH_WAY_BILL_DESC_ID = 322,
	//fish type handle id
	EOT_GAME_FISH_TYPE_HANDLE_ID = 323,
	EOT_GAME_FISH_TYPE_HANDLE_DIANCICANNON_ID = 324,
	EOT_GAME_FISH_TYPE_HANDLE_DNTG_ID = 325,
	EOT_GAME_FISH_TYPE_HANDLE_FIRESTORM_ID = 326,
	EOT_GAME_FISH_TYPE_HANDLE_FREEZE_ID = 327,
	EOT_GAME_FISH_TYPE_HANDLE_FULLSCRBOMB_ID = 328,
	EOT_GAME_FISH_TYPE_HANDLE_HAIWANGCRAB_ID = 329,
	EOT_GAME_FISH_TYPE_HANDLE_KINDBOMB_ID = 330,
	EOT_GAME_FISH_TYPE_HANDLE_LIGHTLINK_ID = 331,
	EOT_GAME_FISH_TYPE_HANDLE_LIGHTNINGJELLYFISH_ID = 332,
	EOT_GAME_FISH_TYPE_HANDLE_MADCOW_ID = 333,
	EOT_GAME_FISH_TYPE_HANDLE_SERIALBOMBCRAB_ID = 334,
	EOT_GAME_FISH_TYPE_HANDLE_SOME_ZUANTOU_ID = 335,
	EOT_GAME_FISH_TYPE_HANDLE_ZUANTOU_ID = 336,
	EOT_GAME_FISH_TYPE_HANDLE_DELAYBOMB_ID = 337,
	EOT_GAME_FISH_TYPE_HANDLE_BLACKHOLEBOMB_ID = 338,
	EOT_GAME_FISH_TYPE_HANDLE_HAISHEN_ID = 339,
	EOT_GAME_FISH_TYPE_HANDLE_GOLDENBULL_ID = 340,
	EOT_GAME_FISH_TYPE_HANDLE_CAISHEN_ID = 341,

	EOT_GAME_FISH_TYPE_HANDLE_FISHPROPSAVER_ID = 342,

	EOT_LINK_ROOM_CONFIG_DESC_ID = 350,
	EOT_GAME_LINK_DESK_HANDLE_ID = 351,
	EOT_LINK_ROOM_MGR_ID = 352,
	EOT_LINK_GAME_SYSTEM_CONTROL_DESC_ID = 353,
	EOT_LINE_LEVEL_DESC_ID = 354,
	EOT_GAME_FAFATA_DESK_HANDLE_ID = 355,
	EOT_GAME_LINK_SETTING_DESC_ID = 356,
	EOT_LINK_GAME_LINEDESKINFO_DESC_ID = 357,
	EOT_LINE_ALGO_DESC_ID = 358,
	EOT_GAME_CHESS_ROBOT_HANDLE_ID = 359,
	EOT_LINK_HM_LINE_GAME_ID = 360,
	EOT_LINK_MINI_GAME_BASE_ID = 361,
    EOT_LINK_MINI_GAME_FREE_ID = 362,
    EOT_LINK_MINI_GAME_MARY_ID = 363,
    EOT_LINK_MINI_GAME_GUESS_ID = 364,
    EOT_LINK_MINI_GAME_SELECT_ID = 365,
	EOT_LINK_MINI_GAME_SHUI_LAI_BAO_ID= 366,
    EOT_LINK_MINI_GAME_BU_BU_GAO_ID = 367,
    EOT_LINK_MINI_GAME_FREE_FU_XING_ID = 368,

	EOT_SG_END_ID = EOT_SUB_GAME_END_ID, //499
} EN_SUBGAME_SHMOBJ_TYPE;
