// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yd_fieldoptions.proto

#ifndef PROTOBUF_yd_5ffieldoptions_2eproto__INCLUDED
#define PROTOBUF_yd_5ffieldoptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace yd_fieldoptions {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_yd_5ffieldoptions_2eproto();
void protobuf_AssignDesc_yd_5ffieldoptions_2eproto();
void protobuf_ShutdownFile_yd_5ffieldoptions_2eproto();


enum message_db_field_type {
  E_FIELDTYPE_NORMAL = 1,
  E_FIELDTYPE_PRIMARYKEY = 2,
  E_FIELDTYPE_INDEX = 3,
  E_FIELDTYPE_UNIQUE_INDEX = 4
};
bool message_db_field_type_IsValid(int value);
const message_db_field_type message_db_field_type_MIN = E_FIELDTYPE_NORMAL;
const message_db_field_type message_db_field_type_MAX = E_FIELDTYPE_UNIQUE_INDEX;
const int message_db_field_type_ARRAYSIZE = message_db_field_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* message_db_field_type_descriptor();
inline const ::std::string& message_db_field_type_Name(message_db_field_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    message_db_field_type_descriptor(), value);
}
inline bool message_db_field_type_Parse(
    const ::std::string& name, message_db_field_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<message_db_field_type>(
    message_db_field_type_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kDbFieldTypeFieldNumber = 41000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::yd_fieldoptions::message_db_field_type, ::yd_fieldoptions::message_db_field_type_IsValid>, 14, false >
  db_field_type;
static const int kDbFieldBufsizeFieldNumber = 41001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  db_field_bufsize;
static const int kDbFieldNotNullFieldNumber = 41002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  db_field_not_null;
static const int kDbFieldAutoIncrementFieldNumber = 40003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  db_field_auto_increment;
static const int kDbFieldArysizeFieldNumber = 41004;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  db_field_arysize;
static const int kDbFieldAutoIncrementValueFieldNumber = 40005;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  db_field_auto_increment_value;
static const int kNoDbFieldFieldNumber = 40006;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  no_db_field;
static const int kDbFieldCommentFieldNumber = 40007;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  db_field_comment;
static const int kFieldTypenameFieldNumber = 42000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_typename;
static const int kFieldArysizeFieldNumber = 42001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  field_arysize;
static const int kFieldBufsizeFieldNumber = 42002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  field_bufsize;
static const int kNoFieldFieldNumber = 42003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  no_field;
static const int kFieldCnameFieldNumber = 43000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_cname;
static const int kFieldSelectIdFieldNumber = 43001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_select_id;
static const int kFieldIdFieldNumber = 43002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_id;
static const int kFieldEnumCnameFieldNumber = 2000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_enum_cname;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace yd_fieldoptions

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yd_fieldoptions::message_db_field_type>() {
  return ::yd_fieldoptions::message_db_field_type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_yd_5ffieldoptions_2eproto__INCLUDED
