// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yd_fieldoptions.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "yd_fieldoptions.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace yd_fieldoptions {

namespace {

const ::google::protobuf::EnumDescriptor* message_db_field_type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_yd_5ffieldoptions_2eproto() {
  protobuf_AddDesc_yd_5ffieldoptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "yd_fieldoptions.proto");
  GOOGLE_CHECK(file != NULL);
  message_db_field_type_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_yd_5ffieldoptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_yd_5ffieldoptions_2eproto() {
}

void protobuf_AddDesc_yd_5ffieldoptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025yd_fieldoptions.proto\022\017yd_fieldoptions"
    "\032 google/protobuf/descriptor.proto*\200\001\n\025m"
    "essage_db_field_type\022\026\n\022E_FIELDTYPE_NORM"
    "AL\020\001\022\032\n\026E_FIELDTYPE_PRIMARYKEY\020\002\022\025\n\021E_FI"
    "ELDTYPE_INDEX\020\003\022\034\n\030E_FIELDTYPE_UNIQUE_IN"
    "DEX\020\004:r\n\rdb_field_type\022\035.google.protobuf"
    ".FieldOptions\030\250\300\002 \001(\0162&.yd_fieldoptions."
    "message_db_field_type:\022E_FIELDTYPE_NORMA"
    "L:9\n\020db_field_bufsize\022\035.google.protobuf."
    "FieldOptions\030\251\300\002 \001(\005:A\n\021db_field_not_nul"
    "l\022\035.google.protobuf.FieldOptions\030\252\300\002 \001(\010"
    ":\005false:G\n\027db_field_auto_increment\022\035.goo"
    "gle.protobuf.FieldOptions\030\303\270\002 \001(\010:\005false"
    ":9\n\020db_field_arysize\022\035.google.protobuf.F"
    "ieldOptions\030\254\300\002 \001(\005:I\n\035db_field_auto_inc"
    "rement_value\022\035.google.protobuf.FieldOpti"
    "ons\030\305\270\002 \001(\005:\0010:;\n\013no_db_field\022\035.google.p"
    "rotobuf.FieldOptions\030\306\270\002 \001(\010:\005false:9\n\020d"
    "b_field_comment\022\035.google.protobuf.FieldO"
    "ptions\030\307\270\002 \001(\t:7\n\016field_typename\022\035.googl"
    "e.protobuf.FieldOptions\030\220\310\002 \001(\t:6\n\rfield"
    "_arysize\022\035.google.protobuf.FieldOptions\030"
    "\221\310\002 \001(\005:6\n\rfield_bufsize\022\035.google.protob"
    "uf.FieldOptions\030\222\310\002 \001(\005:8\n\010no_field\022\035.go"
    "ogle.protobuf.FieldOptions\030\223\310\002 \001(\010:\005fals"
    "e:4\n\013field_cname\022\035.google.protobuf.Field"
    "Options\030\370\317\002 \001(\t:8\n\017field_select_id\022\035.goo"
    "gle.protobuf.FieldOptions\030\371\317\002 \001(\t:1\n\010fie"
    "ld_id\022\035.google.protobuf.FieldOptions\030\372\317\002"
    " \001(\t:<\n\020field_enum_cname\022!.google.protob"
    "uf.EnumValueOptions\030\320\017 \001(\t", 1226);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "yd_fieldoptions.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    41000, 14, false, false,
    &::yd_fieldoptions::message_db_field_type_IsValid);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    41001, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    41002, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    40003, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    41004, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    40005, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    40006, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    40007, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    42000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    42001, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    42002, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    42003, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    43000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    43001, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    43002, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::EnumValueOptions::default_instance(),
    2000, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_yd_5ffieldoptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_yd_5ffieldoptions_2eproto {
  StaticDescriptorInitializer_yd_5ffieldoptions_2eproto() {
    protobuf_AddDesc_yd_5ffieldoptions_2eproto();
  }
} static_descriptor_initializer_yd_5ffieldoptions_2eproto_;
const ::google::protobuf::EnumDescriptor* message_db_field_type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return message_db_field_type_descriptor_;
}
bool message_db_field_type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::yd_fieldoptions::message_db_field_type, ::yd_fieldoptions::message_db_field_type_IsValid>, 14, false >
  db_field_type(kDbFieldTypeFieldNumber, static_cast< ::yd_fieldoptions::message_db_field_type >(1));
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  db_field_bufsize(kDbFieldBufsizeFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  db_field_not_null(kDbFieldNotNullFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  db_field_auto_increment(kDbFieldAutoIncrementFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  db_field_arysize(kDbFieldArysizeFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  db_field_auto_increment_value(kDbFieldAutoIncrementValueFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  no_db_field(kNoDbFieldFieldNumber, false);
const ::std::string db_field_comment_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  db_field_comment(kDbFieldCommentFieldNumber, db_field_comment_default);
const ::std::string field_typename_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_typename(kFieldTypenameFieldNumber, field_typename_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  field_arysize(kFieldArysizeFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  field_bufsize(kFieldBufsizeFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  no_field(kNoFieldFieldNumber, false);
const ::std::string field_cname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_cname(kFieldCnameFieldNumber, field_cname_default);
const ::std::string field_select_id_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_select_id(kFieldSelectIdFieldNumber, field_select_id_default);
const ::std::string field_id_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_id(kFieldIdFieldNumber, field_id_default);
const ::std::string field_enum_cname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  field_enum_cname(kFieldEnumCnameFieldNumber, field_enum_cname_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace yd_fieldoptions

// @@protoc_insertion_point(global_scope)
